### ISSUE TITLE
Splitting up the LOADfile

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/ApplicationPattern#105]
Current LOADfile is of multiple purposes.
It contains configuration information, application data and also some secrets.

The current LOADfile shall be split into
- CONFIGfile : config.json
- DATAfile *) : data.json
- SECRETSfile : secrets.?

*) the current DATAfile, which is the LOADfile plus some additional information, which is necessary for executing testing in Postman shall be named PMfile in future.

CONFIGfile shall be alike the current LOADfile, but it shall be limited to the configuration of the application.
Particularly the Profile section shall be reduced to profile instances that represent configuration information, but not application data.
Secrets like operation-keys shall be removed.
The CONFIGfile shall still define the initiation state of the application.
It will be provided as a part of the individual specification.
Its data format shall follow the ONF information modelling structure.

DATAfile shall either contain the application data or the connection information towards a database.
Content and structure shall be encapsulated by the individual application implementation.
It will not be part of the specification.
There will be no defined initiation state of the application.
There is no modelling structure prescribed, but the implementer has to provide open documentation.

SECRETSfile shall contain information, which needs to be protected against reading and changing.
It has to be encrypted, but its format shall be reused by all applications.
It will be provided as a part of the ApplicationPattern.
It's part of the definition of the initiation state of the application.
Its data format shall follow the ONF information modelling structure.

**Comment by PrathibaJee** [comment]
Regarding separating operation-key and maintaining it in a secret file , I could able to understand the proposal in a high level. 
Whether this SECRETSfile contains information about operation-servers/clients with operation-keys represented in the ONF format ? 
**If so,** 
can we have the following , 
1. Operation-keys will be present in the CONFIGFile itself
2. Operation-Keys will be encrypted
3. CONFIGFile will be protected against unauthorized reading and changing

This will reduce the complexity in the server side implementation ,
- reading operation-key of an operation-client in one file, 
- mapping the operation-client uuid in another file
- finding out the tcp information from the mapped instance's server

Also by implementing the point(2) and (3) , we can ensure the safety of the key.

**Comment by MartinSunal** [comment]
CONFIGfile - sounds reasonable. However, it should also contain information about DB connection and such settings which are needed for application to start.

DATAfile - contains domain specific application data. I assume/believe that in 99% of business applications this is database. In case there is existing file/database at start of application, it will be used. Otherwise the application will create one.

SECRETSfile - I think secrets can be part of CONFIGfile or CONFIGfile can reference to SECRETSfile. However, in both cases you need to encrypt and decrypt them somehow what usually requires a key which needs to be injected to application at start or application can obtained it from somewhere during start. Another aspect is that in case of DB you need to provide username and password, in case of some 3rd party apps some api-key, etc. to application before it starts. So you need to somehow encrypt these info (with the same mechanism as application will use for decrypting) before you put it to SECRETSfile/CONFIGfile and then start application and giving it a key for decryption. There is a lot of "somehow" which need to be specified.

In general, if there is a requirement to run 2 or more replicas of an application then storing any data to file during runtime will cause problems.

**Comment by openBackhaul** [comment]
Current LOADfile is of multiple purposes.
It contains configuration information, application data and also some secrets.

**Decision made on ApplicationImplementation call on 20th of May 2022:**

The current LOADfile shall be split into
- CONFIG : config.json
- APPDATA : applicationName.json (or multiple files also of different file formats) or database (applicationName.*)

**CONFIG:**
- It shall be alike the current LOADfile, but it shall be limited to the configuration of the application.
- If application data is stored in a data base, information required for connection to the data base shall also be seen as part of the configuration, which is to be stored in the CONFIG.
- If application data is stored in one or several files, name and location of the of these files shall also be seen as part of the configuration, which is to be stored in the CONFIG.
- Particularly the Profile section shall be reduced to profile instances that represent configuration information, but not application data.
- Secrets like operation-keys shall be encrypted.
- The CONFIG shall still define the initiation state of the application.
- It will be provided as a part of the individual specification.
- Its data structure shall follow the ONF information modelling structure.

**APPDATA:**
- It shall contain the application data.
- Content and structure shall be encapsulated by the individual application implementation.
- It will not be part of the specification.
- There will be no pre-defined initiation state of the application.
- In case there is existing file/database at start of application, it will be used. Otherwise the application will create one.
- There is no modelling structure prescribed, but the implementer has to provide open documentation.

**Comment by openBackhaul** [comment]
In the [decision made on 20th of May 2022](https://github.com/openBackhaul/ApplicationPattern/issues/105#issuecomment-1132657728) it is stated:
.
>
> * APPDATA : applicationName.json (or multiple files also of different file formats) or database (applicationName.*)
> 
Last part of the text implies every application potentially owning an individual database with an individual name in its folder or container. 
Later it has been decided that all or several applications will share the same database instance and access by REST interface.
An ElasticsearchClient has been defined for that purpose in issue #235.
This change in the OAS does not lead to any change in the CONFIGfile of the ApplicationPattern, because it is individual to the respective application, whether it connects to one or even several databases.
.
>
> * If application data is stored in one or several files, name and location of the of these files shall also be seen as part of the configuration, which is to be stored in the CONFIG.
>
An FileProfile for storing such data has been defined in issue #287.
This change in the OAS does not lead to any change in the CONFIGfile of the ApplicationPattern, because it is individual to the applications, whether it uses one or even several files for storing application data.
.
>
> * Particularly the Profile section shall be reduced to profile instances that represent configuration information, but not application data.
>
A separate issue #289 has been created for tracking of the removal of obsolete Profile definitions and instances from the ApplicationPattern specification, incl. the CONFIGfile
