### ISSUE TITLE
OAS : generic pattern defined for uuid in OAM layer : Basic Part needs update

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationPattern#109]
In OAS, the pattern for uuid is specified for each API request of OAM layer.
As per understanding, the uuid is formed in the following combination. 
**Abbreviation of application-name - release-number - profile/server/client info - unique identifier number.**

Issue description :
- The uuid pattern specified is more generic for for application-name and release-number placeholders. 
  - For example, the existing pattern for http-server is **-\d+-\d+-\d+-http-s-\d{4}$.**
    This pattern could possibly accept any combination of letters in the beginning of the string and thus the restriction for application-name and release-number gets affected.

Possible solution:
- Pattern could be updated for accepting more specific uuid . For example, ^[a-z]+-\d+-\d+-\d+-http-s-\d{4}$

**Comment by openBackhaul** [comment]
Find "pattern: '-\d+-\d+-\d+-" and Replace by "pattern: '**^[a-z,*]+**-\d+-\d+-\d+-".
In divergence from proposal above * has been added to allow examples using "*" symbol for expressing a place holder.
