### ISSUE TITLE
Modify : Rest client to record server unavailability in EaTL application

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/ApplicationPattern#123]
In all the applications , We have the EaTL logging for each api in its corresponding methods in the controller/*.js.
This will log the following in the EaTL , 
- server side error(500) during the processing of the request.
- successful processing(200/204)
- Earlier before centralizing the auth validation , the authorization and authentication failures will be captured to the EaTL. But now , its not. So we have to fix this. separate issues will be created in the corresponding repositories.
- If a service is not available due to server unavailability(503) , that information will not be logged to EaTL.
    For example , 
    - TAR is down 
    - RO sends registration notification to TAR
    - The Rest call to TAR will be failed
    - But this will not be captured in the EaTL , because we have EaTL logging in the service processing logic and not in the service calling end.

This is a loophole in the application pattern server implementation and needs to be fixed.

**Proposal :**
Including logic in the ApplicationPattern/rest/client/EventDispathcher.js , need to enhance the dispatchEvent to log service unavailability failure messages.

**Comment by openBackhaul** [comment]
Wouldn't it be more straight and clean to implement the logging on the client side?

Which current assumptions and design aspects would be affected by this change?
