### ISSUE TITLE
Fix : The value of detailed-logging-is-on to be changed to boolean value in load file

### ISSUE THREAD

**Issue by vanithavalluripalli9** [openBackhaul/ApplicationPattern#129]
During get operation of OAM service /core-model-1-4:control-construct/logical-termination-point={uuid}/layer-protocol=0/operation-client-interface-1-0:operation-client-interface-pac/operation-client-interface-configuration/detailed-logging-is-on  it is failing with error.
**Reason :**
As per the OAS , the type of the value of the detailed-logging-is-on attribute is boolean ,
![thumbnail_image001](https://user-images.githubusercontent.com/102719190/173015376-ab17de38-c818-4784-8e41-afe21be2e368.png)
But as per the load file , the value is a string.
![thumbnail_image002](https://user-images.githubusercontent.com/102719190/173016518-8d79e8dc-7db4-45b3-bdef-2078e008ab36.png)
**Proposal :**
In the load file , the value for the “detailed-logging-is-on” should be changed from string to boolean (ie) “false” to false as below
![thumbnail_image003](https://user-images.githubusercontent.com/102719190/173016819-961bd803-f3ab-4d17-ade0-1f5635e0a0e1.png)

**Comment by openBackhaul** [comment]
AP CONFIGfile has to be changed in 834 from "false" to false.

**Comment by openBackhaul** [comment]
Fixed via web interface to avoid hassle with open pull-requests.
