### ISSUE TITLE
response-body validation failing with Internal error 500 for the generic representation services

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/ApplicationPattern#143]
After including the response-body validation in the server side implementation.
For API's like /v1/start-application-in-generic-representation , /v1/inform-about-application-in-generic-representation, /v1/inform-about-release-history-in-generic-representation response body validation is failing with Internal error 500
**Reason :** 
According to OAS specification, in response body it is expecting the value to be "String"(S in Capital letter) but according to server side implementation the code is "string"(s in small letter) 
In the server side code , the typeOf method is returning “string"(s in small letter)  and not “String"(S in Capital letter). This is the reason for the failure.
**Proposal :**
Either in the server side code , the value “string"(s in small letter)  needs to be modified to “String"(S in Capital letter)
(or)
In the OAS specification , the value “String"(S in Capital letter) needs to be changed to “string"(s in small letter) 

> Note : Issue reported by @IswaryaaS

**Comment by openBackhaul** [comment]
'String' shall be replaced by 'string' in the OAS of ApplicationPattern and all other applications.
