### ISSUE TITLE
Update StructureOfUuids.md documentation

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/ApplicationPattern#150]
There are additional things I just noticed about the  [ApiSegment][AppNumber][SeqNumber]  part.

1. The document describes how this part should look like in case of a client or a server: but what about if the object type is one of the other possibilities, i.e. fc, fc, link or p?

3. from the description for client and server, we always end up with 4 digits: 
- ApiSegment = 1 digit (0,1,2,3) plus
- AppNum = 1 digit (0 for server) or 2 digits (00..32 for client) plus
- SeqNum = 2 digits (for server) or 1 digit (for client)

What if there are more services than uuids with those 4 digits? especially the MWDI has multiple 100 services...

**Comment by openBackhaul** [comment]
Bzgl. The document describes how this part should look like in case of a client or a server: but what about if the object type is one of the other possibilities, i.e. fc, fc, link or p?
Hätte ich gerne ein Issue, dass ich zu einem späteren Zeitpunkt bearbeiten kann.
Jetzt ergänzt wurde „
_The consequence definitions for ApiSegment, ApplicationNumber and SequenceNumber apply for Clients and Servers._  
_Similar rules for ForwardingDomain, ForwardingConstruct, Link and Profile will be added during writing the guidelines for elaborating the ForwardingList and the ProfileList._  
“

Bzgl. from the description for client and server, we always end up with 4 digits:
Habe ich folgendes ergänzt, aber noch nicht gemerged.
If the defined numbers of digits would not suffice in some case (e.g. provided servers or clients towards one application) an additional digit must be added to all UUIDs at this application.

**Comment by kmohr-soprasteria** [comment]
Hi Thorsten,

alles klar, ich erzeuge ein neues Issue für das Thema.

Br
Katharina

Von: Thorsten Heinze ***@***.***
Gesendet: Montag, 27. Juni 2022 13:41
An: openBackhaul/ApplicationPattern ***@***.***>
Cc: MOHR Katharina ***@***.***>; Author ***@***.***>
Betreff: Re: [openBackhaul/ApplicationPattern] Update StructureOfUuids.md documentation (Issue #150)


Bzgl. The document describes how this part should look like in case of a client or a server: but what about if the object type is one of the other possibilities, i.e. fc, fc, link or p?
Hätte ich gerne ein Issue, dass ich zu einem späteren Zeitpunkt bearbeiten kann.
Jetzt ergänzt wurde "
The consequence definitions for ApiSegment, ApplicationNumber and SequenceNumber apply for Clients and Servers.
Similar rules for ForwardingDomain, ForwardingConstruct, Link and Profile will be added during writing the guidelines for elaborating the ForwardingList and the ProfileList.
"

Bzgl. from the description for client and server, we always end up with 4 digits:
Habe ich folgendes ergänzt, aber noch nicht gemerged.
If the defined numbers of digits would not suffice in some case (e.g. provided servers or clients towards one application) an additional digit must be added to all UUIDs at this application.

-
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FopenBackhaul%2FApplicationPattern%2Fissues%2F150%23issuecomment-1167247013&data=05%7C01%7Ckatharina.mohr%40soprasteria.com%7C0f7ae51028904f37fafe08da5831e952%7C8b87af7d86474dc78df45f69a2011bb5%7C0%7C0%7C637919268646066587%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=VhQ3EsrNzZGbZMg%2BzNG8yc03U0RsHjUCsIpRHHVNu%2BA%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FANVRLE7KLB2Y6HNBOZVNNY3VRGHMZANCNFSM5Z6BGCMQ&data=05%7C01%7Ckatharina.mohr%40soprasteria.com%7C0f7ae51028904f37fafe08da5831e952%7C8b87af7d86474dc78df45f69a2011bb5%7C0%7C0%7C637919268646066587%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Vz%2BQBzWDuHHporxDGCj4XC7HIbdpHowvVWEZ6lZxp2c%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

Sopra Steria SE - Vorsitzender des Aufsichtsrates: Cyril Malargé - Vorstand: Christian Wrage (Sprecher), Frédéric Munch - Sitz der Gesellschaft: Hamburg - HRB 151350 Amtsgericht Hamburg - USt-ID-Nr.: DE118671351

**Comment by kmohr-soprasteria** [comment]
Hi Thorsten,

mit nur einem Digit kommen wir da aber doch für Fall 2 nicht hin, wenn es mehr als 100 Services sind. Müsste es dann nicht eher so sein, dass wir 1 digit anhängen, wenn wir tatsächlich damit hinkommen oder halt 2 wenn es mehr Services sind?

Br
Katharina

Von: Thorsten Heinze ***@***.***
Gesendet: Montag, 27. Juni 2022 13:41
An: openBackhaul/ApplicationPattern ***@***.***>
Cc: MOHR Katharina ***@***.***>; Author ***@***.***>
Betreff: Re: [openBackhaul/ApplicationPattern] Update StructureOfUuids.md documentation (Issue #150)


Bzgl. The document describes how this part should look like in case of a client or a server: but what about if the object type is one of the other possibilities, i.e. fc, fc, link or p?
Hätte ich gerne ein Issue, dass ich zu einem späteren Zeitpunkt bearbeiten kann.
Jetzt ergänzt wurde "
The consequence definitions for ApiSegment, ApplicationNumber and SequenceNumber apply for Clients and Servers.
Similar rules for ForwardingDomain, ForwardingConstruct, Link and Profile will be added during writing the guidelines for elaborating the ForwardingList and the ProfileList.
"

Bzgl. from the description for client and server, we always end up with 4 digits:
Habe ich folgendes ergänzt, aber noch nicht gemerged.
If the defined numbers of digits would not suffice in some case (e.g. provided servers or clients towards one application) an additional digit must be added to all UUIDs at this application.

-
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FopenBackhaul%2FApplicationPattern%2Fissues%2F150%23issuecomment-1167247013&data=05%7C01%7Ckatharina.mohr%40soprasteria.com%7C0f7ae51028904f37fafe08da5831e952%7C8b87af7d86474dc78df45f69a2011bb5%7C0%7C0%7C637919268646066587%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=VhQ3EsrNzZGbZMg%2BzNG8yc03U0RsHjUCsIpRHHVNu%2BA%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FANVRLE7KLB2Y6HNBOZVNNY3VRGHMZANCNFSM5Z6BGCMQ&data=05%7C01%7Ckatharina.mohr%40soprasteria.com%7C0f7ae51028904f37fafe08da5831e952%7C8b87af7d86474dc78df45f69a2011bb5%7C0%7C0%7C637919268646066587%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Vz%2BQBzWDuHHporxDGCj4XC7HIbdpHowvVWEZ6lZxp2c%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

Sopra Steria SE - Vorsitzender des Aufsichtsrates: Cyril Malargé - Vorstand: Christian Wrage (Sprecher), Frédéric Munch - Sitz der Gesellschaft: Hamburg - HRB 151350 Amtsgericht Hamburg - USt-ID-Nr.: DE118671351
