### ISSUE TITLE
UUID numbering schemes for FD, FC, Link, Profile

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/ApplicationPattern#151]
The rules for building UUIDs in [Structure for UUIDs](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/SpecifyingApplications/StructureOfUuids/StructureOfUuids.md)  currently are not complete. 

The descriptions on what values to assign for the building blocks ApiSegment, ApplicationNumber and SequenceNumber currently only apply for Clients and Servers. Similar rules for ForwardingDomain, ForwardingConstruct, Link and Profile still need to be added.
(For now there will only be a note in the documentation stating that it is planned to elaborate on that when ForwardingList und ProfileList guidelines will be written.)

**Comment by openBackhaul** [comment]
Rules for building UUIDs in [Structure for UUIDs](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/SpecifyingApplications/StructureOfUuids/StructureOfUuids.md) have to be complemented for the listed object types in the following chapters:

ApiSegment  
- [ ] ForwardingDomain
- [ ] ForwardingConstruct
- [ ] Link
- [x] Profile 

ApplicationNumber  
- [ ] ForwardingDomain
- [ ] ForwardingConstruct
- [ ] Link
- [x] Profile 

SequenceNumber
- [ ] ForwardingDomain
- [ ] ForwardingConstruct
- [ ] Link
- [x] Profile

**Comment by openBackhaul** [comment]
Has been covered in issue #160, respectively its pull-request #233.
