### ISSUE TITLE
Fix wrong link to "Creating ProfileList" in SpecifyingApplications.md

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/ApplicationPattern#154]
The link for "Creating ProfileList" in [SpecifyingApplications](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/SpecifyingApplications/SpecifyingApplications.md) doesn't lead to the "Creating ProfileList" page, but to the page for creating the ServiceList.

**Comment by openBackhaul** [comment]
Fixed
