### ISSUE TITLE
OAS : /v1/inform-about-application-in-generic-representation : API Documentation description

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationPattern#155]
Issue path: 
 /v1/inform-about-application-in-generic-representation -> responses(200) -> schema -> properties -> consequent-action-list -> properties -> request -> description

Issue description:
In the above path, the URL corresponding to API Documentation is */v1/inform-about-api*, but currently we use the swagger UI as a API reference which expose the UI in "http://application_address:application_port/*docs*"

Proposal:
Shall we update the API documentation description as */docs* which is provided by swagger as  a default path, or a regex pattern that could allow greedy text, so that we can customize the API Documentation URI in future

**Comment by IswaryaaS** [comment]
The issue was raised based on specification 0.0.2b. 
However, in specification 1.0.1, the properties of consequent-action-list are referencing to action-profile. 
Following are the observations regarding the update
- As per the descriptions provided, the consequent-action-list will contain a list of all action-profile items present in the load-file (since there is no explicit condition for which specific action-profile to be considered for /v1/inform-about-application-in-generic-representation or /v1/inform-about-release-history-in-generic-representation)
- The property "request" is intended to contain configurable attributes like tcp-s(local-address and local-port). 
    - Either the complete request is formed from server-side logic and the action-profile-capability/request only contains the reference for those attributes or it is pre-defined with complete URI. If the value is pre-defined in load-file, can we have this attribute under configuration class instead of capability for future configurations of values.
- Accessing the attributes of action-profile through OAM layer might be needed. If so, we would need to introduce separate  APIs in OAM layer for each attributes

**Comment by PrathibaJee** [comment]
Also , please kindly look into the following analysis , 

In the server side code , adding the following option to the expressAppConfiguration will change the swagger UI url path from  "/docs" to "/v1/inform-about-api"
```
swaggerUI : {
        swaggerUIPath: '/v1/inform-about-api'
    }
```
This change will launch the swagger UI in the path baseurl/v1/inform-about-api

![image](https://user-images.githubusercontent.com/62344562/178257017-568d7420-b025-429c-8e21-90e66f6ae434.png)
