### ISSUE TITLE
required:false ignored in request body of /v1/register-yourself

### ISSUE THREAD

**Issue by vanithavalluripalli9** [openBackhaul/ApplicationPattern#159]
In OAS , the required parameter for requestBody of v1/register-yourself is mentioned as false .

So , as a part of request , for register-yourself service when we are passing empty request body the request should be successful.

**Problem :**

But , the v1/register-yourself request is failing indicating that the requestBody should have the required properties

"registry-office-application" ,
"registry-office-application-release-number" ,
"registry-office-operation" ,
"registry-office-address" ,
"registry-office-port"

**Root cause :**

In OAS , the request-body for register-yourself is specified as mentioned below :

Where required:false parameter of requestBody is being overwritten by “required” parameter of the requestBody/content/application/json/schema.

So the request is failing indicating required properties are not present.

**Further analysis for proposal :**

If we remove the “required” keyword from requestBody/content/application/json/schema , this issue will be resolved .

But , there will be no validation in case if we pass the request body with the properties.

So , we have to analyze further to propose a solution for this.

**Comment by openBackhaul** [comment]
I am wondering about the purpose of the first required statement (required: false), if it would not have any effect in case there is a second required statement, because if the second required statement would be missing, it seems not to be necessary for the first required statement to represent a false.

Please, investigate into the following direction:
First required statement representing false and a minProperties: 5 statement used instead of the second required statement.

**Comment by vanithavalluripalli9** [comment]
**Summary :** 

Please note that Method#1 and Method#2 mentioned below are not working Method#3 is working and it will resolve the problem.

 **Method#1 : Reason why request body required: false is being overridden by the schema's required property :**  

According to the below mentioned github issue it is an existing issue and they specified a workaround of using x-nullable : true 

https://github.com/spec-first/connexion/issues/1317

We tried to add x-nullable : true as workaround suggested in the above mentioned GitHub issue but it was not working it is still throwing the same error that required fields are missing.

On further research , we found there is one more open issue and bug related to the x-nullable. Please find the link to the github issue of the same

https://github.com/go-swagger/go-swagger/issues/1601

**Method#2 : Using minProperties:5 property instead of second required(schema's required) property :** 

 After adding minProperties:5 , maxProperties:5 and additionalProperties:false 
properties instead of second required statement and if we send a request with empty request body it is failing with the reason : 

"message": "request.body should NOT have fewer than 5 properties"

As a result , we removed minProperties:5 property alone and kept maxProperties:5 and additionalProperties:false and if we send request . Please find the scenarios mentioned below and the respective results.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:\Users\Vanitha\AppData\Local\Temp\msohtmlclip1\01\clip.htm">
<link rel=File-List
href="file:///C:\Users\Vanitha\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Scenario | Output
-- | --
Sent request with empty body | Successful
Sent request with all the 5 parameters in   the request body | Successful
Sent request with adding wrong parameters   in the request body | Giving error as   "message": "request.body   should NOT have additional properties" which is expected
Sent request with less number of   parameters (less that 5) | Successful (Working as expected   but it is limitation in our scenario)



</body>

</html>


**Method#3:** 

As above method was having limitations and not working as expected we tried using oneOf keyword and defined the schema as mentioned and it is working as expected in all the above scenarios mentioned in the Method#2 without any limitations. 

 oneOf:
     - maxProperties: 0
        description: Empty request body
     - type: object
         required:
              - registry-office-application
              - registry-office-application-release-number
              - registration-operation
              - registry-office-address
              - registry-office-port

Kindly , guide us whether we can proceed with Method#3 as solution .

**Comment by openBackhaul** [comment]
Many thanks for investigating.
The solution Method#3 sounds great.
Will immediately apply the proposal.
