### ISSUE TITLE
Refine concepts of profileList + profileInstanstanceList

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/ApplicationPattern#163]
I would find it helpful if the document [Concepts of ProfileList and ProfileInstanceList](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/SpecifyingApplications/ConceptOfProfileList/ConceptOfProfileList.md) would contain some example for what is described there - it doesn't necessarily have to be the actual code. Maybe just some overview picture which makes the relationship between both clearer.

E.g. something like
![profilePic](https://user-images.githubusercontent.com/57349523/177152612-281b9f49-8afc-4db5-9eec-6ad01bb9d6ed.png)

**Comment by openBackhaul** [comment]
Thanks for providing the picture.
Just added it to [Concepts of ProfileList and ProfileInstanceList](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/SpecifyingApplications/ConceptOfProfileList/ConceptOfProfileList.md).
