### ISSUE TITLE
Improve Profile(Instance)List documentation: bigger picture/examples

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/ApplicationPattern#165]
From the already available descriptions of the profileList and profileInstanceList it was kinda hard to grasp for me how the profiles are related to the other parts of the code. For the overall understanding it would be helpful if there would be at least a short explanation of the bigger picture in the Concept of Profile/ProfileInstanceList (or own page), even if detailed descriptions would be included later on in other documents.

E.g. in [Creating a ProfileInstanceList](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/SpecifyingApplications/CreatingProfileInstanceList/CreatingProfileInstanceList.md) under New Profiles section there is the sentence:

> Be aware that you just need to describe the structuring of configuration information. Application data shall be encapsulated by the application.

For someone new to the concept I find it hard to really understand what this sentence means in terms of the specification.

----
As I did not understand where the profile information comes into play, I had a look at the OAS yaml and e.g. found the following code snippet (markdown breaks the fomattings):

> /core-model-1-4:control-construct/profile-collection/profile={uuid}/integer-profile-1-0:integer-profile-pac/integer-profile-capability/integer-name:
>     parameters:
>       - in: path
>            name: uuid
>            required: true
>            schema:
>                type: string
>                pattern: '-\d+-\d+-\d+-integer-p-\d{4}$'
>                example: '*-0-0-1-integer-p-0000'

So as far as I understand it, I'm having the path/url which has the path parameter {uuid} and I would then need to define an integer profile instance inside the profileInstanceList. I still had the old profiles.yaml in my repo, where I found the following profileInstance:

>   - profile-name: IntegerProfile
>     uuid: integer-p-0000
>     integer-name: maximumNumberOfEntries
>     unit: records
>     minimum: 0
>     maximum: 17
>     configured-value: 8

Which would then mean if I see the pattern above, that my integer-p-0000 matches and the uuid could be a number between 0 and 17. 
Of course I could add additional IntegerProfiles, e.g. integer-p-0001 with min=20 and max=120; then the uuid could be either between 0-17 or 20-120. 

---- 
Maybe something like that could be given as an example and also together with an example of the application data that's encapsulated and not related to the profiles.

**Comment by openBackhaul** [comment]
Purpose of Profiles and Examples have been described in [Concept of Profiles](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/SpecifyingApplications/ConceptOfProfiles/ConceptOfProfiles.md).
Did you find it?

**Comment by openBackhaul** [comment]
Details on the OAS and the CONFIGfile will be described in separate documents.

Formulated a little more text in the Purpose section:

### Purpose of Profiles  
Profiles are for holding configuration information.  
Most the configuration information is for documenting traffic relationships (e.g. HttpServer, OperationClient).  
Profiles are for configuration information that is not directly related to an individual interface.  
Contained information could relate e.g.  
* to all or a group of interfaces  
* or to a process or calculation that is executed inside the application.  

Examples:  
- If there would be an application, which is documenting records about some type of events, it would probably make sense to make the number of events, which are to be recorded before deleting the eldest record, configurable.  
- If there would be an application for calculating some value from input from the network, there could be one or several static parameters in that formular. Potentially, it would make sense to make these parameters available for configuration during runtime of the application.  

Configuration information is not to be mixed with application data.  
While data is entering the application through body or response body of services, configuration information is read and set through GET and PUT requests in the OaM section of the REST API.  
Moreover structuring and storing of application data is implementation specific (could be e.g. a database), while structuring of configuration information is subject to specification and storing is happening in the CONFIGfile.
