### ISSUE TITLE
Complete uuids in templates

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/ApplicationPattern#166]
The uuids inside the templates from the repository are not complete, e.g. in the profile/profileInstance yaml templates.

profiles yaml:
- uuid: -string-p-10
- uuid: -action-p-10

profileInstances:
-  uuid: action-p-1001
-  uuid: action-p-1002

As far as I understood you, you wanted to change the templates to include the AppID and release-number information there as well.
(Or did I misunderstand that somehow?)

**Comment by openBackhaul** [comment]
In regards to the profiles yaml, the UUIDs are represented as far as they are already known during creation of the ProfileList.
I added a "*" for the unknown applicationName and "??" for the two missing digits of the SequenceNumber.

In regards to the profileInstances yaml, I added a "*" for the applicationName, "??" for the two missing digits of the SequenceNumber and a comment that requests for entering concrete values.
