### ISSUE TITLE
Decide on handling of ip addresses inside GitHub

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/ApplicationPattern#199]
IP and port lists are not provided inside the serviceList documentation, as the GitHub documentation is public and these are confidential TEF information.
However - the ips are seen in the code (e.g. the serviceList), as the code is also public.

Therefore, it needs to be decided on how this should be handled.
Possibly actual IPs could be replaced by placeholders and the real IPs then just be added when the application is implemented.
(E.g. if app is to be run in different environments, this anyway needs to be done.)

**Comment by openBackhaul** [comment]
@kmohr-soprasteria: Until potential switch towards BaseURLs, fake TCP/IP addresses have to be used within the specifications (e.g. ServiceList, CONFIGlist, etc.). These fake addresses are unique and harmonized, so they can be replaced by script before testing in the SDN laboratory or going into live.  
Please, find the [list of addresses](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/TestingApplications/Infrastructure/SdnLaboratory/IpAddresses/IpAddresses.md).
