### ISSUE TITLE
Refine StructureOfReleaseNumbers tagging

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/ApplicationPattern#201]
In [Structure of Release Numbers](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/SpecifyingApplications/StructureOfReleaseNumbers/StructureOfReleaseNumbers.md) tagging is described. I think it might be helpful to extend the description a bit to make it more clear what exactly happens. 

> Situation 5: The specification 2.0.0 has been finished and develop Branch got merged into main Branch for publishing it to potential implementers. The new content of the main Branch gets tagged with "2.0.0_spec".
> 
> Situation 6: The specification 2.0.0 has been implemented and the implementer merged his code into the main Branch. The new content of the main Branch gets tagged with "2.0.0_imp".

From my understanding the tag is only added in the main branch and the development branch stays with 2.0.0 - it would be good if this would be written down explicitly here to avoid confusion.

A second point that is also not entirely clear to me is how the tag is added to the main branch. From the workflow documentation I would now assume that we will first fork a new release branch from the development branch. So would the tag then be added there already or would we apply this only and directly in the main branch?

**Comment by openBackhaul** [comment]
@kmohr-soprasteria: Added a little text to make it even more explicit ([Structure of Release Numbers](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/SpecifyingApplications/StructureOfReleaseNumbers/StructureOfReleaseNumbers.md)).
