### ISSUE TITLE
Update Create ServiceList default issue: reviewers selection list

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/ApplicationPattern#205]
The issue for creating the serviceList has the point:

> Create a Pull-Request from your local feature branch into the develop branch; define another ApplicationOwner to be reviewer; assign the Pull-Request to OpenBackhaul

When I tried to add another application owner by username it did not work. Only other user shown for me is OpenBackhaul. 
It would be good if we would document somewhere how to add other users to the selection menus.

**Comment by openBackhaul** [comment]
Just sent an email to the ApplicationOwners to check, whether another applicationOwner adding a comment to the Issue suffices to make him/her available for being chosen as reviewer.
Please, close the issue based on the feedback.
Many thanks.

**Comment by openBackhaul** [comment]
Sending a comment doesn't work.
New idea:
Configure all ApplicationOwners to be Collaborator on the repository, but define the individual ApplicationOwner to be CodeOwner (according to [github doc](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners))

Consider different CodeOwner files for main and develop branch.
Check gitignor for preventing the CodeOwner file from develop branch to overwrite the one in main branch.

**Comment by openBackhaul** [comment]
@kmohr-soprasteria: Sorry, concept doesn't work and needs further investigations before.
Zwar führt der Eintrag in CODEOWNERS tatsächlich dazu, dass die gelistete Person zum Review des Merge-Requests aufgefordert wird.
Falls die Person zum Merge-Request nicht zustimmt, macht das aber auch keinen Unterschied.
Dies ist umso problematischer, da man den Inhalt von CODEOWNERS bei der Gelegenheit auch gleich überschreiben kann.
Also im Moment noch keine Lösung für den Review durch einen anderen ApplicationOwner weil noch keine Methode gefunden die Rechte mehrerer Collaboratoren zu unterscheiden.
