### ISSUE TITLE
Update the "ImplementingApplications" page with the "table of content" of the underlying Sub-topics

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/ApplicationPattern#211]
- [ ] Create a table of content with the topics and sub-topics  inside the [Application implementation](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ImplementingApplications/ImplementingApplications.md).please refer the attachment. [Topics inside application implementation.txt](https://github.com/openBackhaul/ApplicationPattern/files/9219118/Topics.inside.application.implementation.txt)
- [ ] update the [Application implementation](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ImplementingApplications/ImplementingApplications.md) with the new content in .md format.

**Comment by openBackhaul** [comment]
Document still has the character of a training (means: puts the content into an order for learning implementing step-by-step).

Instead it should:

- Document shall only contain basic concepts and designs directly related to implementing applications (step-by-step guidelines for individual activities might be added later). It shall be ordered by subject, not by training sequence.

- Basic concepts of the ApplicationPattern shall be moved to [Elements of the ApplicationPattern](https://github.com/openBackhaul/ApplicationPattern/blob/PrathibaJee/issue211/doc/ElementsApplicationPattern/ElementsApplicationPattern.md)

- Step-by-step training including homework and tests shall be moved into [a document in a template repository](https://github.com/openBackhaul/ApplicationImplementerTrainingTemplate/blob/develop/doc/RoadmapToImplementingApplications.md), which will be replicated for every new trainee.

**Comment by PrathibaJee** [comment]
Closing this issue as visual studio is having a problem to create a pull request. Created a new issue https://github.com/openBackhaul/ApplicationPattern/issues/256.
