### ISSUE TITLE
Update release-number as per the StructureOfReleaseNumbers concepts

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/ApplicationPattern#213]
In the following documents , "release number" samples are not as per the concept mentioned in the [StructureOfReleaseNumbers](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/SpecifyingApplications/StructureOfReleaseNumbers/StructureOfReleaseNumbers.md) .
1.	[ImplementingApplications#ControlConstruct.md](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ImplementingApplications/UnderstandingTheRequirement/EntitiesOfLoadFiles/ControlConstruct.md)
2.	[ImplementingApplications#LogicalTerminationPoint.md](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ImplementingApplications/UnderstandingTheRequirement/EntitiesOfLoadFiles/LogicalTerminationPoint.md) 

Require to change the release-number information.

**Comment by openBackhaul** [comment]
Got fixed with pull-request #230, too.
