### ISSUE TITLE
Update syntax of the UUID as per the standard defined in the "Structure of UUIDs"

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/ApplicationPattern#214]
In the following documents , Syntax of the UUIDs are not as standard as available in the [StructureOfUuids](https://github.com/openBackhaul/ApplicationPattern/blob/openBackhaul/issue160/doc/SpecifyingApplications/StructureOfUuids/StructureOfUuids.md)
1.	[ImplementingApplications#ControlConstruct.md](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ImplementingApplications/UnderstandingTheRequirement/EntitiesOfLoadFiles/ControlConstruct.md)
2.	[ImplementingApplications#LogicalTerminationPoint.md](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ImplementingApplications/UnderstandingTheRequirement/EntitiesOfLoadFiles/LogicalTerminationPoint.md) 
3.	[ImplementingApplications#ForwardindConstruct.md](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ImplementingApplications/UnderstandingTheRequirement/EntitiesOfLoadFiles/ForwardindConstruct.md)

Require to modify the syntax provided for the UUIDs.

**Comment by openBackhaul** [comment]
Pull-request under review.
