### ISSUE TITLE
Implementation to be updated on new UUID format

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/ApplicationPattern#232]
A [new UUID format](https://github.com/openBackhaul/ApplicationPattern/blob/openBackhaul/issue160/doc/ElementsApplicationPattern/Names/StructureOfUuids/StructureOfUuids.md) has been defined mainly to avoid administrating and sending an ApplicationNumber for supporting UUID creating for Clients.  
A description of the [new UUID format](https://github.com/openBackhaul/ApplicationPattern/blob/openBackhaul/issue160/doc/ElementsApplicationPattern/Names/StructureOfUuids/StructureOfUuids.md) can be found in the ApplicationPattern documentation.  

Implementation need to be adapted to the new UUID format.

**Comment by PrathibaJee** [comment]
In the implementation , the following issues covers the changes required to be adapted in the Application and Basic services packages , 

1.  https://github.com/openBackhaul/ApplicationPattern/issues/345
2.  https://github.com/openBackhaul/ApplicationPattern/issues/346

**Comment by PrathibaJee** [comment]
Closing this issue as the sub-tasks created to implement this concept are closed. Thanks
