### ISSUE TITLE
/v1/register-yourself is not working for the first time

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/ApplicationPattern#241]
When a "new application" is deployed first , the "new application" will not have the correct ip address and port in the tcp-server configuration in the initial load file.
So when we send "register-yourself" from this application , the correct ip address will not be registered in the RegistryOffice(RO).

Consider the following scenario, 

![image](https://user-images.githubusercontent.com/62344562/184341557-4ae40274-d53b-4fed-a6f7-4a7e264f70ec.png)

Also , in order to configure the tcp-server , we can use the following two OAM services 

1. /core-model-1-4:control-construct/logical-termination-point={uuid}/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-interface-configuration/remote-address
2.  /core-model-1-4:control-construct/logical-termination-point={uuid}/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-interface-configuration/remote-port
 
This configuration is not possible without a connection to the AdministratorAdministration(AA) application. So , before connecting to the RegistryOffice , the application should be connected to AA to configure the tcp-server. Incase of the TinyApplicationController , we are following the below deployment order to resolve this, 

![image](https://user-images.githubusercontent.com/62344562/184342458-56ff958a-2330-41db-83af-fb2f6e15fed7.png)

But incase of a new bussiness application, this is not possible as the new application cannot get authorized by the default operation-key.

### **Proposal#1 : Script to replace fake IPs with actual during docker image creation**
During docker image creation , 
the initial ip address of the client applications in the CONFIGfiles should be replaced with actual IP address and port.
the own application ip-address should be replaced with the proposed IP address adn port.
By doing so , the application will have correct IP address and port information in the tcp-server and client in the initial load file.

### **Proposal#2 : Running the containers in Kubernetes**
In kubernetes , we can expose a container's exposed port as a service
Each such service have a unique name
By using the service name , communication accross containers can be established.
In the initial load file , if we represent the service name in the tcp-server/client configuration , if the containers are running in kubernetes , then communication across containers can be automated without manual interuption. 

### **Proposal#3 : Including a APIGW for all applications**
Details in the attachment , 
[220804 APIGW approach for East-West communication.docx](https://github.com/openBackhaul/ApplicationPattern/files/9316088/220804.APIGW.approach.for.East-West.communication.docx)

**Comment by openBackhaul** [comment]
The ApplicationPattern and its implementation shall (as far as possible) not depend on a specific environment.
So, the applications just running in a Kubernetes environment or just running together with an APIgateway would not be preferred.

So, running the applications with plain and simple TCP/IP addresses must be possible.
Of course, running the application together with APIgateway or Kubernetes would be nice to have, too.
But as long as there is no clear and urgent driver to go into these directions, it would be 2nd priority.

I would like the result to support the following two processes:
The application properly to start up with ...
- ... a manually (or automatically) created and adapted CONFIGfile (#250).
- ... a default CONFIGfile that gets automatically adapted after registering at the TinyApplicationController (#251).

**Comment by openBackhaul** [comment]
The advantages of a potential adaption of the design towards Kubernetes seem not to be that significant (instantiation would be improved, but configurability would suffer) to justify delay in producing implementations.
Creating an environment specific CONFIGfile by script plus facilitating handing over TCP/IP addresses of the Server and the OldRelease seems to be a double solid solution of the indicated problem.
Both changes have been documented and tracked in separate issues.
