### ISSUE TITLE
List for translating fake IP addresses into the TCP/IP addresses of the live environment

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/ApplicationPattern#246]
The CONFIGfile contains all data that is necessary to establish the connections, which are required for properly operating the application.
TCP/IP addresses, operation names and application release number might depend on the environment (e.g. SDN test laboratory or live network) in which the application gets instantiated in.
As a consequence the CONFIGfile has to be adapted to the environment before instantiation.
This adaption shall be automated.

For supporting the automation, fake IP addresses have to be put into the CONFIGfile during specification.
Fake IP addresses will be replaced by environmental specific addresses during creating the container.

- [x] List for translating fake IP addresses into the TCP/IP addresses of the live environment to be created and to be maintained.
- [x] List has to cover current release numbers and operations, too.
- [x] Responsibility for updating the list has to be defined and documented.

! Please, regard IP addresses not to be published on public platforms !

**Comment by openBackhaul** [comment]
Assign to vanithavalluripalli9

**Comment by Rajithapitta** [comment]
“A list that consists of the application-name , release-number and original-ip-address , original-port , original-protocol for the lab environment is maintained in the CICD pipeline to change the config file details”
It is implemented as per requirement and using it in current environment.
