### ISSUE TITLE
Script for translating fake IP addresses into environment specific

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/ApplicationPattern#247]
The CONFIGfile contains all data that is necessary to establish the connections, which are required for properly operating the application.
TCP/IP addresses, operation names and application release number might depend on the environment (e.g. SDN test laboratory or live network) in which the application gets instantiated in.
As a consequence the CONFIGfile has to be adapted to the environment before instantiation.
This adaption shall be automated.

For supporting the automation, fake IP addresses have to be put into the CONFIGfile during specification.
Fake IP addresses will be replaced by environmental specific addresses during creating the container.

- [ ] Write script for reading list of environment specific TCP/IP addresses and replacing the fake IP addresses in the CONFIGfile.
- [ ] Release numbers also to be updated in the CONFIGfile.
- [ ] Script to be embedded into the pipeline for deploying into SDN laboratory
- [ ] Script to be embedded into the pipeline for deploying into live network

**Comment by PrathibaJee** [comment]
We developed a script , that 

- takes a mapping file as an input which consists of the original "ip address" and "port" for every  "application-name" and "release-number" in the environment, finds the instance and update it. The input file will be in the following format , 
```
  {
            "category": "TinyApplicationController",
            "abbreviation" : "TAR",
            "component": "TypeApprovalRegister",
            "release": "0.0.1",
            "fake-tcp-ip": "1.1.3.2",
            "fake-tcp-port": 3002,
            "original-tcp-ip": "127.0.0.1",
            "original-tcp-port": 3002
        }

```
- Updates the tcp instances , based on the mapped http instance for the "application-name" and "release-number"

And would like to share the information that , we are not utilizing the "fake ip address" and "port" details.
Having the original IP address, application-name , release-number as per the environment is sufficient to perform this operation.

Kindly let me know is this is fine or ? do we have to include an additional check after finding the tcp instance , if the existing ip is the fake one assigned for this application and then replace the address.
Or
Can we remove this entries realted to fakeips from the input file.

**Comment by openBackhaul** [comment]
I have some doubts about making "application-name" and "release-number" as an input to the replacement of the ip-address and port:
- the logic requires "application-name" and "release-number" being there. If the attributes have different names or aren't there, the replacement fails.
- since a couple of weeks there might be multiple TcpClients per HttpClient. Consequently, there might be multiple ip-address/port pairs per application-name/release-number (e.g. HTTP and HTTPS).

Wouldn't it be easier to just search for string "1.1.3.2" and replace it by string "127.0.0.1"?

**Comment by PrathibaJee** [comment]
Sorry , looks like this issue closed by mistake.

**Comment by openBackhaul** [comment]
Implementation states that filling in the locally correct combination of IP address and TCP port can be based on ApplicationName and ReleaseNumber.  

Consequently, the concept of FakeIP addresses can be abandoned.
The local host IP address (127.0.0.1) shall be applied as a standard instead.

- Documentation to be changed  
- FakeIP table to be adapted to show always the local host IP address, **but individual TCP ports**
- FakeIP to be disregarded in the script for adding locally correct IP addresses and TCP ports.
