### ISSUE TITLE
Deployment guidelines to be complemented in regards of replacing fake IP addresses

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/ApplicationPattern#249]
The CONFIGfile contains all data that is necessary to establish the connections, which are required for properly operating the application.
TCP/IP addresses, operation names and application release number might depend on the environment (e.g. SDN test laboratory or live network) in which the application gets instantiated in.
As a consequence the CONFIGfile has to be adapted to the environment before instantiation.
This adaption shall be automated.

For supporting the automation, fake IP addresses have to be put into the CONFIGfile during specification.
Fake IP addresses will be replaced by environmental specific addresses during creating the container.

- [x] The deployment guidelines shall describe how to operate the script inside the pipeline for deploying into the live network environment.

**Comment by Rajithapitta** [comment]
The has fixed and information is available in below document.
https://github.com/openBackhaul/ApplicationPattern/blob/develop/server/FakeToOriginalIPConverter/README.md

Hence closing the issue.
