### ISSUE TITLE
Add own TCP/IP and TCP/IP of OldRelease to body of /v1/register-yourself 

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/ApplicationPattern#251]
The CONFIGfile contains all data that is necessary to establish the connections, which are required for properly operating the application.
TCP/IP addresses, operation names and application release number might depend on the environment (e.g. SDN test laboratory or live network) in which the application gets instantiated in.
In case the CONFIGfile has not properly been adapted, the adaption shall automatically been done during embedding.
A small subset of addresses is required in that case.

The OAS of the ApplicationPattern to be changed in the following regards:
- [ ] The body of the /v1/register-yourself shall be complemented by the own-ip-address, own-port, old-release-ip-address and old-release-port.
- [ ] Sending these attributes shall not be mandatory.
- [ ] In case not sent within the body, existing values from the CONFIGfile shall be applied.

**Comment by PrathibaJee** [comment]
The current proposal looks good. For sending the old-release tcp information sharing an alternate proposal  , 

**Alternate proposal :**
While sending "embed-yourself" , Registry office shall send the previous version's ipaddress and port information to the new application.

The OAS of the ApplicationPattern to be changed in the following regards:
- [ ] The body of the _/v1/embed-yourself_ shall be complemented with additional two attributes _old-release-ip-address_ and _old-release-port_.
- [ ] If there is no old release of the same application available in RO then sending the ip-address of the same application shall be allowed
- [ ]  Sending these attributes shall be mandatory.

**Comment by openBackhaul** [comment]
**Problem statement:**  
The CONFIGfile should contain all data that is necessary to establish the connections, which are required for properly operating the application.
TCP/IP addresses, operation names and application release number might depend on the environment (e.g. SDN test laboratory or live network) in which the application gets instantiated in.
In case the CONFIGfile would not have been properly adapted, the adaption shall automatically been done during embedding.
A small set of additional address attributes in some requests are required to support that.

The OAS of the ApplicationPattern shall be modified in the following regards:
- [ ] The body of the _/v1/register-yourself_ shall be complemented by _own-ip-address_ and _own-port_ of the new application.
- [ ] Sending these attributes shall not be mandatory.
- [ ] Call backs 
- [ ] In case not sent within the body, existing values from the CONFIGfile shall be applied.
- [ ] The body of the _/v1/embed-yourself_ shall be complemented by _old-release-ip-address_ and _old-release-port_.
- [ ] If there would be no old release of the same application registered at the RegistryOffice application, sending the _own-ip-address_ and _own-port_ of the new application shall be allowed.
- [ ]  Sending these attributes shall be mandatory.
