### ISSUE TITLE
Guideline for formulating Issues

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/ApplicationPattern#27]
Development of documentation, specification and code shall be driven by issues (commits shall reference the respective issue).

Issues have to contain meaningful information and advice for completing the task, even by a third person.

[FormulatingIssues.md](https://github.com/openBackhaul/ApplicationPattern/blob/tsi/doc/PreparingSpecifying/FormulatingIssues/FormulatingIssues.md) to be filled with concise, but also comprehensive guidance on how to formulate issues.

It has to be regarded that Issues shall be used not just for bug tracking, but also for feature definition (means: not just fixing existing problems, but also defining next steps in the development).

Maybe, one or several schema for being copied into the issue and filled with individual information, could be provided in [FormulatingIssues.md](https://github.com/openBackhaul/ApplicationPattern/blob/tsi/doc/PreparingSpecifying/FormulatingIssues/FormulatingIssues.md).

Potential sources of information could be:
- [How We Write Github Issues](https://wiredcraft.com/blog/how-we-write-our-github-issues/)
- [Writing a proper GitHub issue](https://medium.com/nyc-planning-digital/writing-a-proper-github-issue-97427d62a20f)
- [7 Tips to Write Flawless Issue Reports on Github](https://tomasvotruba.com/blog/2019/07/08/7-tips-to-write-flawless-issue-report-on-github/)
- [Best Practices for Using GitHub Issues](https://www.backhub.co/blog/best-practices-for-using-github-issues)

**Comment by xiidoz** [comment]
> Maybe, one or several schema for being copied into the issue and filled with individual information, could be provided in [FormulatingIssues.md](https://github.com/openBackhaul/ApplicationPattern/blob/tsi/doc/PreparingSpecifying/FormulatingIssues/FormulatingIssues.md).

I think a good way to help contributors use the correct issue guidline, would be using the GitHub integrated feature of [issue templates](https://github.com/openBackhaul/ApplicationPattern/issues/templates/edit). There, default templates for different cases (e.g. new feature or bug) can be selected and edited to fit our needs. Then, on creating an issue, you can select one of the given templates, that is then used to prefill the issue description.

**Comment by openBackhaul** [comment]
Yes, sure. Katharina could you please analyse the options. Many thanks in advance.

**Comment by openBackhaul** [comment]
Guideline has been provided by @kmohr-soprasteria and can be found at [FormulatingIssue](https://github.com/openBackhaul/ApplicationPattern/blob/tsi/doc/PreparingSpecifying/FormulatingIssues/FormulatingIssues.md).
Templates have been analysed, but not jet been build.
