### ISSUE TITLE
server : life-cycle-state type DEPRECATED in response header is as per ONF core-model : not filtered

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationPattern#274]
The life-cycle state is an enumeration of values. In which "DEPRECATED" is a type.

Problem statement:
When the life-cycle-state is "DEPRECATED" for an operation-server or operation-client instance, the response header is producing the complete value present in load-file as "operation-server-interface-1-0:LIFE_CYCLE_STATE_TYPE_DEPRECATED". But it should be just "DEPRECATED". 

Note: This filtering is working fine for other types of life-cycle-state.

**Comment by PrathibaJee** [comment]
Issue fixed in the pull request https://github.com/openBackhaul/ApplicationPattern/pull/277. Hence closing this issue.
