### ISSUE TITLE
Specifig Implementation required to cover Data Protection Requirements into AA, EaTL, OamLog

### ISSUE THREAD

**Issue by alattoch** [openBackhaul/ApplicationPattern#302]
1. AdministartorAdministration: Named-User need to be deleted after on Month. Information that theNamed-User will leave, is expected as eMail to the product owner  

2. "OaM-Log: Need to be cleared after 1 Month automatically 

3. "Execution and Trace - Log: Need to be cleared after 1 Month automatically 

Those above are official reqirements by the Telefonica Data Protection Organization. The requirements above are in the official DGSVO Reporsitory assigned to the product owner Thorsten Heinze.

**Comment by openBackhaul** [comment]
@alattoch : Above requirements cannot be specified by OAS, CONFIGfile or testcases. Could you please contact implementers to agree how to assure implementation.

**Comment by alattoch** [comment]
Will be fixed in Version 2.0 as part of elastic stack 
...
This policy says, that new index is created every 15 days and old index will be kept for another 15 days after rollover and then it is removed. That means we have 30 days history.
2.	Modify Logstash output in logstash pipeline config:
output {
  elasticsearch {
    hosts => "http://172.29.145.205:9200"
    ilm_enabled => "true"
    ilm_rollover_alias => "controller-karaflog-rollover"
    ilm_pattern => "{now/d}-000001"
    ilm_policy => "keep10m-policy"
  }
..
