### ISSUE TITLE
Integration and acceptance testsuite execution in Newman environment

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/ApplicationPattern#308]
> Note : Created this issue to document the problem , analysis , workaround  and progress regarding the execution of acceptance and integration test suite collection in Newman environment.

### Problem Description :
While running the integration and acceptance testsuite in the Newman environment , the testsuite execution stopped because of the following error message , 

```
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x5582463a0e74 node::Abort() [node]
 2: 0x5582463a0ec2  [node]
 3: 0x558246598aaa v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0x558246598d25 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0x55824694a0a6  [node]
 6: 0x55824694a1e4  [node]
 7: 0x55824695c70b v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
 8: 0x55824695cec9 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0x55824695e2a6 v8::internal::Heap::CollectAllAvailableGarbage(v8::internal::GarbageCollectionReason) [node]
10: 0x55824695f878 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [node]
11: 0x55824692bfeb v8::internal::Factory::AllocateRawArray(int, v8::internal::PretenureFlag) [node]
12: 0x55824692c488 v8::internal::Factory::NewFixedArrayWithFiller(v8::internal::Heap::RootListIndex, int, v8::internal::Object*, v8::internal::PretenureFlag) [node]
13: 0x5582468f0fa5  [node]
14: 0x558246b62aba v8::internal::Runtime_GrowArrayElements(int, v8::internal::Object**, v8::internal::Isolate*) [node]
15: 0x26889115bf1d 

```

### Analysis : 
The following factors are checked in the vm where Newman environment is available , 
1. Monitored the memory and CPU consumption using the `top command`. And in the top command , we could able to see a higher utilization of the CPU. While monitored this in detail , noticed that the CPU utilized by the Jenkin user is only less than 10% of CPU. So , the utilization of CPU in regards to the Newman process is reasonable.
2. We noticed that some other unwanted process were also running in the same vm which is utilizing the CPU. So killed those unwanted process in this VM.
```
top - 12:06:17 up 468 days,  7:06,  1 user,  load average: 1.67, 1.33, 1.30
Tasks: 383 total,   2 running, 381 sleeping,   0 stopped,   0 zombie
%Cpu(s): 13.0 us,  0.8 sy,  0.0 ni, 86.0 id,  0.0 wa,  0.2 hi,  0.0 si,  0.0 st
MiB Mem :  15872.9 total,   1756.3 free,  12117.7 used,   1998.9 buff/cache
MiB Swap:   7940.0 total,   7209.5 free,    730.5 used.   3366.8 avail Mem

   PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
3820173 git       20   0 1023452 622544  22252 R  99.0   3.8   0:21.86 bundle
1921517 git       20   0 1966144 830672  22276 S   2.7   5.1  16688:00 bundle
4160889 root      20   0   23.3g   4.0g  21592 S   2.3  25.8  40732:46 java
596641 gitlab-+  20   0  719724  16356   5888 S   1.0   0.1 633:17.26 node_exporter
596668 gitlab-+  20   0 3817408 224036  39488 S   1.0   1.4   2986:33 prometheus
```
3. Further , we noticed that the node version in the server is v10 , and noticed in the [post](https://stackoverflow.com/questions/53230823/fatal-error-ineffective-mark-compacts-near-heap-limit-allocation-failed-javas) there is a memory leak or difference between how Node.js <= 10 and Node.js > 10 manage memory. So , upgraded the node version to latest (ie) V16. And allocated 16 GB memory for the Newman process 'export NODE_OPTIONS=--max_old_space_size=16384'

By doing the points 2 and 3 , in the GCP , we are able to resolve the issue related to memory and we can able to generate reports.

**Note : The average integration test suites execution time is 2 hrs.**

Whereas in the testbed , the acceptance test suites execution time is comparatively higher than the integration test suites as the number of requests are more , still we the memory issue for few applications. 
For example : 
ApplicationLayerTopology takes more than 10 hrs to complete the execution
And after applying the workaround (point 2 and 3) also , the suits are stopped because of the "JavaScript heap out of memory" issue.
Continuing investigation with the acceptance test suite.

**Comment by Rajithapitta** [comment]
As discussed prepared a dummy suite to reproduce the issue and tested, the issue is reproduced on multiple environments from Jenkins and local servers.
Run the dummy suites with below multiple options from postman and newman.
Connectionlive+proxy takes long time for dummy suite
Connectionlive+noproxy takes less time for dummy suite
Connectionclose+proxy takes less time for dummy suite
Connectionclose+noproxy takes less time for dummy suite

Had discussion with team and analyzed the reports, based on it's proxy settings taking long time.
Proxy settings changed as per environment and restarted the servers . 
Tested with dummy suite and other applications suites which is working fine taking less time for each request.
