### ISSUE TITLE
Update Fake IP Addresses document due to TAC v2

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/ApplicationPattern#315]
The [Fake IP Addresses](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/TestingApplications/Infrastructure/SdnLaboratory/IpAddresses/IpAddresses.md) page contains now the entries for both TAC apps with release 1.0.0 and release 2.0.0.

If we decide now to already go fully with the TAC v2 in the app owner specifications, it would probably be a good idea to include some information about that for the app owners. 
- Either a short note before the table, that they should use the TAC v2 entries and not the TAC v1 ones 
- or there could also be an additional *comment* column in the table, where we note that.
- What I could also imagine is to move those v1 entries to an own section with an own table where there's stuff that should not be actively put into specifications anymore but which is still needed, as we still have it in place. (If there will be multiple apps later on which will require multiple releases, the current table could otherwise become cluttered.)

**Comment by openBackhaul** [comment]
@kmohr-soprasteria : Please, 
- review and potentially merge the pull-request #318 
- close this issue
