### ISSUE TITLE
Implementation to be updated in ApplicationPattern for the Generic representation mechanism 

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/ApplicationPattern#348]
As per the latest changes for the version2.0.0 , the generic representation response needs to be formulated based on the action-profile and the response-profile.

Create a file GenericRepresentation.js module in server/applicationPattern/applicationPattern/services and include the following mechanism , 

**Response-value-list :**
1. Find the list of response-profiles based on the response-profile-capability/operation-name equals to the req.url
2.  Formulate the following attributes of the response-value-list as per the following logic , 
      - Field-name : derive it from response-profile-capability/field-name              
              If “field-name” consists of “static-field-name” , consider the available value as it is
              If “field-name” consists of "field-name-reference" , the value is a OAM reference and figure out the value pointed by the reference              
      - Value : derive it from response-profile-configuration/value
              If “value” consists of “static-value” , consider the available value as it is
              If “value” consists of "value-reference" , the value is a OAM reference and figure out the value pointed by the reference
      - Datatype - consider it from response-profile-capability/datatype

**Consequent-action-list :**
1. Find the list of action-profiles based on the action-profile-capability/operation-name equals to the req.url
2. Formulate the following attributes of the response-value-list as per the following logic , 
     - Label : derive it from action-profile-capability/label
     - display-in-new-browser-window : derive it from action-profile-capability/display-in-new-browser-window
     - request : request comprises of a complete url “<protocol>://<address>:<port>/<operation>”, which will be derived from the following four attribute in action-profile-configuration/request, 
                  protocol - derive it from value pointed by the OAM reference in the "protocol-reference" 
                  address - derive it from value pointed by the OAM reference in the "address" , either it is “ipv-4-address-reference” or “domain-name-reference”
                  port - derive it from value pointed by the OAM reference in the "port-reference" 
                  operation - derive it from value pointed by the OAM reference in the "operation-reference" 
     - input-value-list – derive it from the action-profile-capability/input-value-list , further the following values can be depicted from , 
                  field-name - derive it from the value of “field-name”
                  unit - derive it from the value of “unit”

**Comment by ManasaBM1** [comment]
after further modification request is replaced by the "consequent-operation-reference"
In action-profile-configuration:
ConsequentOperation- derive it from value pointed by the OAM reference in the "consequent-operation-reference"
