### ISSUE TITLE
Replacing 'https' and enclosing URL in callbacks with quotes

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationPattern#355]
As per https://github.com/openBackhaul/ApplicationPattern/issues/331 and  https://github.com/openBackhaul/ApplicationPattern/issues/344, an additional attribute called "_local-protocol_" and "_remote-protocol_ are added at TcpServer and TcpClient instances respectively for dynamically choosing http or https while consuming operations.

Required changes:

OAS -  Callback URL:
- [x] the protocol "https" in URL of callbacks to be replaced by actual reference to protocol 
- [x] enclosing the URL at callbacks with quotes for avoiding syntax error

**Comment by openBackhaul** [comment]
Sorry, tested back and forth.
Problem: API editor in Postman does not successfully validate the above proposal.
Have chosen a different solution, which looks like:
````
url: #[/core-model-1-4:control-construct/logical-termination-point=*-1-0-0-tcp-c-bm-ro-2-0-0-000/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-interface-configuration/remote-protocol]://[/core-model-1-4:control-construct/logical-termination-point=*-1-0-0-tcp-c-bm-ro-2-0-0-000/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-interface-configuration/remote-address/domain-name or /core-model-1-4:control-construct/logical-termination-point=*-1-0-0-tcp-c-bm-ro-2-0-0-000/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-interface-configuration/remote-address/ip-address/ipv-4-address]:[/core-model-1-4:control-construct/logical-termination-point=*-1-0-0-tcp-c-bm-ro-2-0-0-000/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-interface-configuration/remote-port][/core-model-1-4:control-construct/logical-termination-point=*-1-0-0-op-c-bm-ro-2-0-0-001/layer-protocol=0/operation-client-interface-1-0:operation-client-interface-pac/operation-client-interface-configuration/operation-name]
````

**Comment by IswaryaaS** [comment]
Yes, I am noticing it is throwing validation error in postman but not in [swagger editor](https://editor.swagger.io/. )

The later proposal looks fine and the schema is validated successfully in both postman editor and swagger editor. 
We can adapt to the later solution.
