### ISSUE TITLE
Problem in the automated provisioning of a new application into SDN Microservice Architecture

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/ApplicationPattern#358]
1. When a new application registers in registry office , RO will forward the new application information to TAR for approval.
2. Once a approver approves the new application , RO will receive the request /v1/regard-updated-approval-status with the approval details    
3. Then, RO will call **v1/embed-yourself**  service in the **new application**.
4. Now , **new application** will send **"v1/bequeath-your-data-and-die"** request to its **old release**.

But until an admin approves a connection between the **"v1/bequeath-your-data-and-die operation-client"** of the new application and the **"v1/bequeath-your-data-and-die operation-server"** of the old application in **Application layer topology**, authorization will be failed.

So automated provisioning of a new application into SDN Microservice Architecture will not happen on receiving the request "v1/embed-yourself" from RO. We have to come up with a proposal to avoid this problem.

**Comment by openBackhaul** [comment]
Comments have not been kept during transferring the issue from RegistryOffice to ApplicationPattern.
The latest state of the discussion was adding an instance of IntegerProfile for configuring some wait time

**Comment by openBackhaul** [comment]
To be checked, whether closed by mistake.

**Comment by openBackhaul** [comment]
I am not sure about the potential solution discussed above.
Please, delay spending efforts in implementing it.

**Comment by openBackhaul** [comment]
Finally, another solution has been specified.

RO is addressing ALT://v1/add-operation-client-to-link for creating the Link 
new application => OldRelease://v1/bequeath-your-data-and-die
before calling NewApplication://v1/embed-yourself.
