### ISSUE TITLE
Ana's Contribution to the Agenda of the Introduction Session

### ISSUE THREAD

**Issue by anacabbar** [openBackhaul/ApplicationPattern#361]
Some questions on MW SDN Applications:

* How do Microservices work together? How are dependecies handled?
* Where is an overview of all the tools and langueges needed for specifying Microservices?

**Comment by openBackhaul** [comment]
**How do Microservices work together**
The address each other by REST interfaces.

**How are dependencies handled?**
There is an information model, which is able to describe these dependencies and their end points.
The information about each dependency is documented according to this information model and stored in a CONFIGfile.
Dependencies can be modified either by
- editing the CONFIGfile in an editor or
- configuring the application via REST API (and the application is updating its CONFIGfile during runtime) or
- the applications of the microservice layer are connection with each other for updating their configuration (also during runtime).

**Where is an overview of all the tools and languages needed for specifying Microservices?**
[Documentation about the Tools and Workflows](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/PreparingSpecifying/PreparingSpecifying.md), which are to be used for specifying the microservices.
