### ISSUE TITLE
Proposal to optimize the value of the attribute consequent-action-list/request

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/ApplicationPattern#362]
> The current design is working fine . This issue consists of a query and a proposal is for an optimized solution. 

In the ConsequentActionList of all the Generic representation services , we have the following three attribute ,  
![image](https://user-images.githubusercontent.com/62344562/200017545-741ea6f0-e21b-4675-958e-43da77af5cfa.png)

In this , we have the request attribute which is a combination of the tcp details + consequent API information , 
![image](https://user-images.githubusercontent.com/62344562/200017579-0aeea2b9-cb7f-4bf2-88ab-33060fc2d8a2.png)

- As of now , the TCP details available in the ConsequentActionList is always the same as the previous request. 

Please kindly let us know your views in the following two points , 
1. Incase , if the ConsequentAction will always points to an API within the same application , then the TCP details shall be removed from the value of the “request” attribute.
2. Incase , in future , if we have a plan to provide a ConsequentAction that points to an API in a different application , then we require no change in the attribute.

**Comment by openBackhaul** [comment]
Many thanks for raising the question and expressing a doubt on the current design.
Keeping door open for referencing websites or operations, which are provided by other applications, would be preferred.
If you would agree, please close the issue.
If you would not agree, please provide further arguments for shortening the String provided in the request attribute.

**Comment by PrathibaJee** [comment]
Thank you for providing your views. 
Agreeing with the point "Keeping door open for referencing websites or operations, which are provided by other applications, would be preferred."
Closing this issue.
