### ISSUE TITLE
Include the attribute "operation-client-update-operation" in the callback of /v1/register-yourself

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/ApplicationPattern#364]
This is in reference to the issue https://github.com/openBackhaul/RegistryOffice/issues/8

Requesting to include the attribute "operation-client-update-operation" in the callback PromptForRegisteringCausesRegistrationRequest of the /v1/register-yourself API. Thanks.

**Comment by openBackhaul** [comment]
In general, all callbacks have to be compared with their original path: statement at the end of all updates in all applications.

In particular, here it is already clear that PromptForRegisteringCausesRegistrationRequest callback has to be updated by an additional operation-client-update-operation attribute.
