### ISSUE TITLE
When to include the optional ElasticSearch attribute "service-records-policy" in the control-construct

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/ApplicationPattern#409]
As per the control-construct response body , for the ElasticSearch client , the attribute service-records-policy is optional. 
As per the discussion in the [comment](https://github.com/openBackhaul/ExecutionAndTraceLog/pull/113#discussion_r1036486104), this information will not be stored in the CONFIG file . This information needs to be fetched from ElasticSearch client.

**Can we follow the steps :**
1. For the /core-model-1-4:control-construct OAM service call 
2. Application that has an ElasticSearch client needs to communicate with ElasticSearch instance to get the service-records-policy information.
3. Incase if there is any failure with the ElasticSearch client interaction (or) if the service-records-policy is not configured (or) not available this information will not be included in the ResponseBody
4. If the details could able to retrive from ElasticSearch , then this shall be include in the ResponseBody.

**Comment by openBackhaul** [comment]
Yes, I confirm this understanding.
Many thanks for moderating the clarification.

**Comment by PrathibaJee** [comment]
Thank you for the confirmation Thorsten. 
I included an implementation issue for version 2.0.0 in the EATL and OL to follow this steps to formulate the responseBody of the ControlConstruct. Hence closing this issue.
