### ISSUE TITLE
Handling of Semantics inside UUIDs

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/ApplicationPattern#454]
According to the [guideline for structuring UUIDs](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ElementsApplicationPattern/Names/StructureOfUuids/StructureOfUuids.md) information about own and targeted applications (e.g. name and release number) have to be used for formulating UUIDs.
This information might change particularly in OperationClients and HttpClients since they are subject to update operations.

**The following rules shall apply as general design principles:**
- **All UUIDs are invariant**: UUIDs get created during instantiation of a logical object. They get deleted while deleting the object. They get never changed during existence of the object.
- **UUIDs have to be treated as fortuitous Strings**: UUIDs shall not be parsed and interpreted for controlling the program flow, but taken as random Strings for identifying logical objects that hold attributes, which are containing the searched information.

It is accepted that these general rules might lead to unaesthetic constellations alike the following hypothetical example:
An HttpClient has been created for addressing CurrentController application of release 1.0.0 and it got the UUID 
_eatl-2-0-0-http-c-cc-1-0-0-000_.
After a while, CurrentController application gets updated.
Its new name is CurrentControllerAddress and the new release is 2.0.0.
Application-name and release-number attributes get updated in existing HttpClients inside consuming applications.
UUIDs of these HttpClients would not change.
Consequently, attributes and UUIDs at the same HttpClient are indicating different application-name and release-numbers.
Due to above rules, it is clear that only the attributes are representing up to date information.

If no objection would be documented here, a corresponding ruling shall be added to the documentation of the ApplicationPattern.

**Comment by PrathibaJee** [comment]
Hi Thorsten , Please find the attached document [221212 Invariant UUID impact Analysis.docx](https://github.com/openBackhaul/ApplicationPattern/files/10210732/221212.Invariant.UUID.impact.Analysis.docx) that describes the scenarios where we wanted to utilize the application-name and release-number to figureout a target operation-client's uuid. But in general, if we use the http-client-configuration/application-name and release-number to figureout the uuid that is fine. And overall no objection for the proposal.

> Change in the application-name will happen very rarely. So the "uuid" and "application-name" will be in sync most of the time.  But , release-number change may happen often , so , "uuid" and "release-number" will be out-of-sync sometimes.

**Comment by PrathibaJee** [comment]
> 

regarding using hardcoded UUIDs inside code, I would like to add the following points (please consider if it is valid) , 

For every new release , the hardcoded values inside the code needs to be updated.
For some scenarios , LTP instances will be created while the application is running(example regard-application). So , insuch cases we cannot able to hardcode uuids and we have to rely on the http-client-configuration/application-name and release-number.

**Comment by PrathibaJee** [comment]
@MartinSunal , regarding using hardcoded UUIDs inside code in the [comment](https://github.com/openBackhaul/ApplicationPattern/issues/454#issuecomment-1348174669), I would like to add the following points (please consider if it is valid) , 
- for every new release , the hardcoded values inside the code needs to be updated.
- for some scenarios , LTP instances will be created while the application is running(example regard-application). So , insuch cases we cannot able to hardcode uuids and we have to rely on the http-client-configuration/application-name and release-number.

**Comment by openBackhaul** [comment]
Hopefully, I manage to make a contribution to clarification of the problem despite not being involved in actual implementation:

- During last week's meeting we said, UUIDs (or parts of it) must not be interpreted for controlling the program flow.
Example: UUID must not be parsed for retrieving the client's application name and release number.

- If we would use hardcoded LTP UUIDs directly in code, we would do the exact same thing.

- Instead, Processing must be based on attributes' values.
Example: RequestBody of _RO://v1/register-application_ contains an attribute called _client-update-operation_.
After receiving the request, the operation-name in some OperationClient has to be updated (or created).
But how to identify the correct OperationClient instance?
  - Wrong way 1: Don't compose the UUID of the OperationClient from values of the _application-name_ and _application-release-number_ attributes, which are sent in the same RequestBody .
  - Wrong way 2: Don't use hard coded information like _client-update-operation_ "always" uses ApiSegment==im and SequenceNumber==001 for composing the UUID.
  - Right way: 
    - (starting from the beginning) The RO received a _RO://v1/register-application_ with a combination of _application-name_ and _application-release-number_ that did not exist before.
    - The RO creates all the LTPs, which are necessary to describe some application in the way the RO sees an application.
    - The RO also creates all the FDs and FCs, which are necessary to describe the forwardings and processings that are available inside the RO on such applications.
    - And the RO also connects all the LTPs, FDs and FCs.
    - Consequently, the correct processing for identifying the searched OperationClient instance is:
      - Hard coded information: The value of the _client-update-operation_ attribute in the RequestBody of the _RO://v1/register-application_ request is required for executing the _ServerReplacementBroadcast_ forwarding. _ServerReplacementBroadcast_ is an invariant value of the name attribute at the FC object, which instantiation is totally under control of the RO application.
      - Search the FD for the FC with name==_ServerReplacementBroadcast_.
      - Search the FC with name==_ServerReplacementBroadcast_ for an output OperationClient that is served by an HttpClient that holds the values of _application-name_ and _application-release-number_ from the RequestBody.
      - Change the value of the _operation-name_ attribute at the OperationClient, which is connected with FC with name==_ServerReplacementBroadcast_ and served by HttpClient that holds the values of _application-name_ and _application-release-number_ from the RequestBody.

Does that make sense?

**Comment by PrathibaJee** [comment]
Yes , that makes sence. 
To identify the already created operation-clients for updation this flow(Right way mentioned in the [comment](https://github.com/openBackhaul/ApplicationPattern/issues/454#issuecomment-1351352216)) will work fine. Thanks.
