### ISSUE TITLE
/v1/update-client to not update an http-client/release-number if already an LTP instance is available

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/ApplicationPattern#464]
Current implementation in the latest ApplicationPattern of /v1/update-client is as follow , 
- Find the http-client instance that satisfies the "application-name" and "old-release-number"
- Updates the new release number and tcp information 

This has a flaw and in case if an application version is already vailable , then two instance of same application will be available in the configuration.
- Find the http-client instance that satisfies the "application-name" and "new-release-number"
- If a ltp instance is already available , then change the tcp-instance if required
- else if a ltp instance for this version is not available , then update the "new-release-number" (and change the tcp-instance if required)

**Comment by openBackhaul** [comment]
👍
