### ISSUE TITLE
UUID parameter schema for Elasticsearch client is incorrect

### ISSUE THREAD

**Issue by MartinSunal** [openBackhaul/ApplicationPattern#472]
Current schema for UUID  parameter does not match ES client : 
 ```
pattern: '^([a-z]{2,6})-([0-9]{1,2})-([0-9]{1,2})-([0-9]{1,2})-es-c-im-([0-9]{3})$'
        example: 'ro-2-0-0-es-c-im-000'
```

**ApplicationPattern+config.yaml, ApplicationPattern+services.yaml**

```
"xx-1-0-0-es-c-es-1-0-0-000"
```

**Comment by PrathibaJee** [comment]
Sorry for not capturing it earlier. Following are the impact analysis for this issue , 

**[StructureOfUuids](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ElementsApplicationPattern/Names/StructureOfUuids/StructureOfUuids.md) :**
- [ ]  example for elastic search needs to remove the APISegment , ctrl + H
      eatl-2-0-0-es-c-is-es-1-0-0-000
      to 
      eatl-2-0-0-es-c-es-1-0-0-000

**[ApplicationPattern.yaml](https://github.com/openBackhaul/ApplicationPattern/blob/develop/ApplicationPattern.yaml) :**
- [ ] To modify the pattern of elastic search (to include appName and releaseNumber) , ctrl + H 
    ^([a-z]{2,6})-([0-9]{1,2})-([0-9]{1,2})-([0-9]{1,2})-es-c-im-([0-9]{3})$
    to
    ^([a-z]{2,6})-([0-9]{1,2})-([0-9]{1,2})-([0-9]{1,2})-es-c-([a-z]{2,6})-([0-9]{1,2})-([0-9]{1,2})-([0-9]{1,2})-([0-9]{3})$

- [ ]  To replace the examples for elastic search , ctrl + H 
      ro-2-0-0-es-c-im-000
      to 
      eatl-2-0-0-es-c-es-1-0-0-000

**Comment by openBackhaul** [comment]
Many thanks for well describing the need for change.
