### ISSUE TITLE
Pattern of UUID paramenter in OAM request .../operation-client-interface-configuration/detailed-logging-is-on

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/ApplicationPattern#516]
For the OAM service to get and put the attribute detailed-logging-is-on , 
As per the uuid pattern defined in specification , APISegment is “bm” . But , as per the config file and the description for the attribute /v1/redirect-service-request-information/service-log-operation , APISegment is “bs”.

**Proposal :**
For the APIs getOperationClientDetailedLoggingIsOn and putOperationClientDetailedLoggingIsOn , path/uuid pattern needs to be changed from 
pattern: '^([a-z]{2,6})-([0-9]{1,2})-([0-9]{1,2})-([0-9]{1,2})-op-c-bm-([a-z]{2,6})-([0-9]{1,2})-([0-9]{1,2})-([0-9]{1,2})-([0-9]{3})$'
to 
pattern: '^([a-z]{2,6})-([0-9]{1,2})-([0-9]{1,2})-([0-9]{1,2})-op-c-bs-([a-z]{2,6})-([0-9]{1,2})-([0-9]{1,2})-([0-9]{1,2})-([0-9]{3})$'

**Impact :** 
In the server , express framework rejects the request while validating the uuid pattern.

**is workaround available ?**
Yes.
This shall be tweaked in the api/openapi.yaml file of the server side code.
putOperationClientDetailedLoggingIsOn : The uuid path parameter defined in this need to change the 
from pattern: "^([a-z]{2,6})-([0-9]{1,2})-([0-9]{1,2})-([0-9]{1,2})-op-c-bm-([a-z]{2,6})-([0-9]{1,2})-([0-9]{1,2})-([0-9]{1,2})-([0-9]{3})$"
to pattern: "^([a-z]{2,6})-([0-9]{1,2})-([0-9]{1,2})-([0-9]{1,2})-op-c-bs-([a-z]{2,6})-([0-9]{1,2})-([0-9]{1,2})-([0-9]{1,2})-([0-9]{3})$"
getOperationClientDetailedLoggingIsOn : The uuid path parameter defined in this need to change the 
from pattern: "^([a-z]{2,6})-([0-9]{1,2})-([0-9]{1,2})-([0-9]{1,2})-op-c-bm-([a-z]{2,6})-([0-9]{1,2})-([0-9]{1,2})-([0-9]{1,2})-([0-9]{3})$"
to pattern: "^([a-z]{2,6})-([0-9]{1,2})-([0-9]{1,2})-([0-9]{1,2})-op-c-bs-([a-z]{2,6})-([0-9]{1,2})-([0-9]{1,2})-([0-9]{1,2})-([0-9]{3})$"

**Comment by openBackhaul** [comment]
Check changing the pattern from
pattern: '^([a-z]{2,6})-([0-9]{1,2})-([0-9]{1,2})-([0-9]{1,2})-op-c-bm-([a-z]{2,6})-([0-9]{1,2})-([0-9]{1,2})-([0-9]{1,2})-([0-9]{3})$'
to
pattern: '^([a-z]{2,6})-([0-9]{1,2})-([0-9]{1,2})-([0-9]{1,2})-op-c-bs-([a-z]{2,6})-([0-9]{1,2})-([0-9]{1,2})-([0-9]{1,2})-([0-9]{3})$'
