### ISSUE TITLE
OAS : Request to include pattern for application name to ensure provided application name is in upper camel case

### ISSUE THREAD

**Issue by vanithavalluripalli9** [openBackhaul/ApplicationPattern#532]
In OAS , currently, any particular pattern is not specified for application name. 

So , as a part of request, the given application name can be of any pattern . For example , if the application name is OamLog it can be given in any of the below mentioned format or more :

- OamLog
- oamlog
- oamLog
- Oamlog

**Problem** :

But , if the given application name contains all lower case letters or only one upperCase letter in it , it would become difficult to form the **OwnApplicationID** part of the  UUID . For example , please find the below mentioned scenarios 

If applicationame is given as **OamLog** , then the UUID would be ol-* , which is composed from the uppercase letters of the application name.

But , if application name is given as **oamlog** or **Oamlog** , then it would become difficult to compose the UUID.

**Proposal :**

To include any one of the below mentioned patterns for application name to ensure the given application name is in upper camel case with atleast 2 uppercase letters in it .

**Pattern** : ([A-Z][a-z0-9!@#$&()\\-`.+,/\"]+){2,} (which allows alphanumeric and special characters)

or 

**Pattern :** ([A-Z][a-z0-9]+){2,} (which allows only alphanumeric)

**Comment by openBackhaul** [comment]
Add ([A-Z][a-z0-9]+){2,} at RO://v1/register-application :: application-name .
At the OAM layer, too.
(Potentially at the regard-application.)

**Comment by openBackhaul** [comment]
Pull-request #539 merged.
