### ISSUE TITLE
OAS : putGenericResponseProfileValue needs to move the example

### ISSUE THREAD

**Issue by ManasaBM1** [openBackhaul/ApplicationPattern#535]
In OAS , currently , the example for putGenericResponseProfileValue request body is present as mentioned below
 
![image](https://user-images.githubusercontent.com/113175652/213091694-53f8be43-3957-4543-9352-2c1f69d26c68.png)

where example is specified for the  property of **response-profile-1-0:value** that is "value-reference" or "static-value" 

**Problem :** 

For implementation we generate server side stub by following steps that are mentioned in the below mentioned link 
[https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ImplementingApplications/Steps2GenerateServerStub/Steps2GenerateServerStub.md](https://ind01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FopenBackhaul%2FApplicationPattern%2Fblob%2Fdevelop%2Fdoc%2FImplementingApplications%2FSteps2GenerateServerStub%2FSteps2GenerateServerStub.md&data=05%7C01%7CMB00776250%40TechMahindra.com%7C7124d20d890e43e5ffdf08daf8a8b2b7%7Cedf442f5b9944c86a131b42b03a16c95%7C0%7C0%7C638095700715786080%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=5JFKiOLawbK47P9vfDP4s91AY69M1mY9KA3UkBpnJgc%3D&reserved=0) . 
While generating server side stub, the swagger editor generated the example  as string because the example is declared for the property of **response-profile-1-0:value** that is "value-reference" or "static-value" which are of type string. But as per specification, it is expected to be an object 

Please find the snapshot of example generated 

![image](https://user-images.githubusercontent.com/113175652/213091924-cdf2adf9-6501-479b-a6d0-dce29dadfa70.png)

**Proposal :** 
To specify the example for request body as mentioned below  : 

![image](https://user-images.githubusercontent.com/113175652/213092018-b21fec4f-28ce-4580-b036-1464b8cd0876.png)

**Comment by openBackhaul** [comment]
Changed as proposed.

**Comment by openBackhaul** [comment]
Pull-request #539 merged.
