### ISSUE TITLE
OAS : getGenericResponseProfileValue needs to move the example

### ISSUE THREAD

**Issue by ManasaBM1** [openBackhaul/ApplicationPattern#536]
In OAS , currently , when response code is 200  , the example for getGenericResponseProfileValue response is present as mentioned below. But as per specification, it is expected to be an object

![gen](https://user-images.githubusercontent.com/113175652/213098311-f9b105bf-046a-4eff-b2c9-252602f5206b.PNG)

where example is specified as an attribute for the property of **response-profile-1-0:value:** that is "value-reference" or "static-value" 

**Problem :** 

For implementation we generate server side stub by following steps that are mentioned in the below mentioned link 
[https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ImplementingApplications/Steps2GenerateServerStub/Steps2GenerateServerStub.md](https://ind01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FopenBackhaul%2FApplicationPattern%2Fblob%2Fdevelop%2Fdoc%2FImplementingApplications%2FSteps2GenerateServerStub%2FSteps2GenerateServerStub.md&data=05%7C01%7CMB00776250%40TechMahindra.com%7C7124d20d890e43e5ffdf08daf8a8b2b7%7Cedf442f5b9944c86a131b42b03a16c95%7C0%7C0%7C638095700715786080%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=5JFKiOLawbK47P9vfDP4s91AY69M1mY9KA3UkBpnJgc%3D&reserved=0) . 
While generating server side stub the swagger editor generated the example as string because it is declared as an example for the property of **response-profile-1-0:value** that is "value-reference" or "static-value" which are of type string. Please find the snapshot of example generated :

![gen2](https://user-images.githubusercontent.com/113175652/213098763-d017588d-5a82-47bb-8e7b-1c85ba1feaeb.PNG)

**Proposal :** 
To specify the example  for the response when response code is 200 as mentioned below : 

![gen2](https://user-images.githubusercontent.com/113175652/213098974-8d6ec7fb-27dd-425f-af46-f611910d5a34.PNG)

**Comment by openBackhaul** [comment]
Changed as proposed.

**Comment by openBackhaul** [comment]
Pull-request #539 merged.
