### ISSUE TITLE
Updating documents of TestingApplications : minor updates

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationPattern#547]
In documentations, https://github.com/openBackhaul/ApplicationPattern/tree/develop/doc/TestingApplications, minor updates can be made for improving content quality. 

Main folder : /docs/TestingApplications
- [x] SDN Laboratory / overview
- [x] Tools / Docker
- [x] Tools / Newman
- [x] SDN Application Pattern Deployment

**Comment by Rajithapitta** [comment]
Fixed as part of https://github.com/openBackhaul/ApplicationPattern/pull/579 and closing the issue.
