### ISSUE TITLE
Installation of Elasticsearch to be used in ApplicationPattern

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationPattern#548]
For applications like ExecutionAndTraceLog, OamLog and ApplicationLayerTopology,  we use Elasticsearch to maintain application data. 

For using them, we need to install them in following environments
-  [x] testbed
- [x] Production

**Comment by Rajithapitta** [comment]
We are reusing the existing ELK setup and kibana which available in on both testbed and GCP environment. We can add our configuration as per application pattern and we can start using the ELK. Shared the details with the team for further testing and validations.
