### ISSUE TITLE
UUID pattern of tcp-client OAM service needs an update

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationPattern#549]
The current pattern provided for uuid of tcp-client-interface-configuration Oam services is 
"^([a-z]{2,6})-([0-9]{1,2})-([0-9]{1,2})-([0-9]{1,2})-tcp-c-([a-z]{2,6})-([0-9]{1,2})-([0-9]{1,2})-([0-9]{1,2})-000$"

The sequence number here is "000". 

Problem statement:
As per understanding, it is possible that more than one tcp-client instance shall be created for an application. 
For example, in RegistryOffice://v1/register-application, we have an attribute called "tcp-server-list". So, while registering an application, an application is allowed to inform it's both HTTP and HTTPS addresses to RO. In this case, multiple tcp-clients would be created for an http-client instance. 

Proposal: 
To update "sequence-number" part of uuid pattern to be **([0-9]{3})** instead of 000. 
So, the pattern would look like "^([a-z]{2,6})-([0-9]{1,2})-([0-9]{1,2})-([0-9]{1,2})-tcp-c-([a-z]{2,6})-([0-9]{1,2})-([0-9]{1,2})-([0-9]{1,2})-**([0-9]{3})**$". 
Updating shall be made in tcp-client/remote-protocol, tcp-client/remote-address and tcp-client/remote-port Oam service APIs. 

Kindly let me know your thoughts

**Comment by openBackhaul** [comment]
Call on 17th of February:
I would prefer having just one cin the Config.
To be checked, whether this is possible.
Issue to be closed, if possible having just one TcpClient.

**Comment by PrathibaJee** [comment]
Kindly please find the following details , 

- Apart from RegistryOffice , for other applications , there should be a single tcp-client.
- In RegistryOffice , to provide “https” information of an application to GenericRepresentation GUI, this tcp-server-list attribute was introduces , where 
    - every registering application shall also provide the “https” information if available
    - if more than 1 tcp information is provided in the tcp-server-list , then for each , a tcp-client will be created in the RO’s config file
- By default , the tcp-client with suffix “-000” will be considered for internal communication within the MicroService Environment
- **(This concept is now obsolete)** For generic representation GUI, the mapped tcp-client uuid in the “Action-profile” will point to the required instance 
Based on the above point , for now , there is no use-case/logic utilizing the 2nd tcp-client

Kindly please consider the following proposal for further discussion , 
(There is a circular dependency)
- Until we decide on the issue https://github.com/openBackhaul/ApplicationPattern/issues/649 , leaving
    - the tcp-server-list attribute in RO/register-application as it is now , 
    - the "sequence-number" part of uuid pattern of the tcp-client-interface-configuration Oam services as it is now
- For internal communication , applications will use the tcp-client with suffix “-000” by default. (In case of wrong IP value , OAM services shall be used to correct them later)

**Comment by openBackhaul** [comment]
Just one thought that came into my mind, while working myself back into the issue:  
If the RO (or any other application) would hold >1 TcpClients, wouldn't that require to change the client update function, too?

**Comment by IswaryaaS** [comment]
Thanks for clarifying @openBackhaul
