### ISSUE TITLE
Update: "Add: Create own GitHub account #8" issue

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/ApplicationPattern#55]
**Is your feature request related to a problem? Please describe.**
Subpoint "Send user name to [ApplicationOwners@openBackhaul.com](mailto:ApplicationOwners@openBackhaul.com)" has no guideline on how to send the user name.

**Describe the solution you'd like**
It could be beneficial to provide some default for the email subject (and mail text). This would allow to easily apply email filters (so such requests are not accidentally overlooked).

**Solution and next next step(s)**  
Check if we want to enforce a specific mail subject (and/or text).

**Comment by openBackhaul** [comment]
Shall be a conventional internal email.
Does not require standardization.
