### ISSUE TITLE
Add pictures to StructureOfInternalForwardings.md

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/ApplicationPattern#551]
I created some pictures for easier understanding, which could be added to the description.
See attached slides.
[InternalForwardings.pptx](https://github.com/openBackhaul/ApplicationPattern/files/10535859/InternalForwardings.pptx)

Also I think there's a typo in the last part: after OperationClient a _ is missing to end the formatting:

> Output: The RegistryOffice is activating its _OperationClient TypeApprovalRegister://v1/regard-application for sending the notification to the TypeApprovalRegister.

**Comment by openBackhaul** [comment]
Had already been done without closing the issue.
