### ISSUE TITLE
Update: update documents for roadmap

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/ApplicationPattern#56]
**Is your feature request related to a problem? Please describe.**
Documents for [roadmap](https://github.com/openBackhaul/ApplicationPatternTemplate/issues/1) need to be reviewed. . 

**Describe the solution you'd like**
Small corrections will be done directly in the documents. For all others issues will be created.

**Solution and next next step(s)**  
Review -> corrections & issues.

**Comment by openBackhaul** [comment]
I assume you made the corrections already, right?

**Comment by openBackhaul** [comment]
After I didn't got an answer, I am assuming the it has been forgotten to close this issue.
