### ISSUE TITLE
putIntegerProfileIntegerValue could be added with description for the configurable value range

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationPattern#561]
In Integer-profile, we have attribute "integer-profile-configuration/integer-value".  
As per understanding, the value of _integer-value_ should be between _minimum and maximum_ values provided in capability class. 
But currently in configuration/integer-value, any integer value that is not within expected range would also be allowed to configure. 

Proposal: 
To ensure avoiding this, can we add a small description like "value between capability/minimum and capability/maximum if available" to "putIntegerProfileIntegerValue" in ApplicationPattern OAS.
Note : since minimum/maximum is an optional attribute in integer-profile/capability class, "if available" statement has been added.

**Comment by openBackhaul** [comment]
In line 6472 a description statement to be add.
Text shall express: Value must be between ...../min and ..../max to be accepted.
