### ISSUE TITLE
putStringProfileStringValue could be added with description for the configurable value

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationPattern#562]
Similar to https://github.com/openBackhaul/ApplicationPattern/issues/561, In string-profile, we have attribute "string-profile-configuration/string-value".
As per understanding, the string-value attribute should be configured with one of attribute present in "enumeration" attribute of capability class. 
But currently in configuration/string-value, any string that is not expected also be allowed to configure.

Proposal: To ensure avoiding this, can we add a small description like "value to be chosen from capability/enumeration if available" to "putStringProfileStringValue" in ApplicationPattern OAS.
Note : since enumeration is an optional attribute in string-profile/capability class, "if available" statement has been added.

**Comment by openBackhaul** [comment]
Call on 17th of February:
In line 6672 a description statement to be add.
Text shall express: String must be one of the options in the enumeration to be accepted, if an enumeration is available in the Capability section.
