### ISSUE TITLE
Update: update guideline for issue template usage

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/ApplicationPattern#58]
**Is your feature request related to a problem? Please describe.**
When issues are created from GitHub at least in the tsi branch a template has to be selected (not sure if this also is the case if a branch is created). In VSCode however, the templates are not shown. 

**Describe the solution you'd like**
If templates always should be followed for issue creation they should somehow be made available in VSCode as well or the guideline should at least cover some additional information about that. (If we say we don't necessarily need to use the templates we can skip this topic.)

**Solution and next next step(s)**  
* Check whether we want to enforce the usage of issue templates and if yes how. 
* Thorsten: decide upon this.

**Comment by openBackhaul** [comment]
I am honestly spoken not convinced from the templates.
E.g. I find it very confusing that the bold text is addressing the guy, who once formulated the issue, but bothering all the guys, who have to read it over and over again.

Starting with documentation should be fine.
If we would see that people don't write proper Issues, we could reconsider the templates.
