### ISSUE TITLE
/v1/update-client logic needs an update

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationPattern#588]
As per specification /v1/update-client shall be updating the already existing current-application-name and current-release-number instances for new future-application-name and future-release-number if a separate instance for {future-application-name, future-release-number} is not available. 
However, the above decision will not be applicable if we have both http-c instances (one for {future-application-name, future-release-number} and one for {current-application-name, current-release-number}). In that case decision made on https://github.com/openBackhaul/ApplicationPattern/issues/509 shall be applied. 

Problem:
Currently, /v1/update-client is creating new http-c instance for new values of future-application-name or future-release-number instead of updating http-c instance of {current-application-name, current-release-number}

**Comment by vanithavalluripalli9** [comment]
The changes in pull request are not updating the applictionName and releaseNumber of current application http-c instance  if http-c instance of future-application-name and future-release-number are not available.
