### ISSUE TITLE
Proposal to move 'getAllApplicationList' method to ApplicationPattern

### ISSUE THREAD

**Issue by DanaSunal** [openBackhaul/ApplicationPattern#613]
This method is used in individualServices/listApplications and it's only difference between various applications (looked at EATL, ALT, OAM) is the forwarding name.

The proposal is about moving the method to AP, with forwarding name as parameter and remove redundant implementation in each application.

Same for method resolveHttpClient/trackNewRelease that is used to track http/tcp server UUID based on FcPort output for forwarding domain 'PromptForBequeathingDataCausesTransferOfListOfApplications'.

**Comment by IswaryaaS** [comment]
In TAR, it would be different, where /v1/list-applications get data from application-data instead of logical-termination-point. Could you please check this and let us know for the workaround

**Comment by DanaSunal** [comment]
I didn't mean to move the service method `exports.listApplications = function (user, originator, xCorrelator, traceIndicator, customerJourney)` , just the one internal that is used to implement this service method. Which means, EATL, ALT, OAM will have (example):
`exports.listApplications = async function (user, originator, xCorrelator, traceIndicator, customerJourney)  {
    await <ApplicationPatternClass>.getAllApplications(forwardingName);
}`

similar to ALT IndividualServicesService.js

`exports.updateAllLtpsAndFcs = async function (body)  {
  await checkIfApplicationExists(body["core-model-1-4:control-construct"]);
  await ControlConstructService.createOrUpdateControlConstructAsync(body);
}`

In TAR (or any other application that needs specific implementation),  the method will stay as it is.

**Comment by IswaryaaS** [comment]
Thanks for clarifying.
