### ISSUE TITLE
Remove username/password attributes of file-profile

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationPattern#643]
In file-profile, we have optional attributes username and password in file-profile which are intended to access a file if protected. 

Server side code shall be included with logic to access a protected file for given user-name and password attributes

**Comment by IswaryaaS** [comment]
**_Dana's analysis:_**
There are two approaches to this problem:
•	- (as described in the issue) restricting the file itself
•	- encrypting the contents

To answer the question about which approach should be used, we need to first determine
what is the purpose of this restriction.
From high-level complexity overview, restricting the file is much more complex and harder to
implement than the encryption. If the purpose is simply to not to expose the contents of the 
data in plaintext to everyone, I would personally prefer the encryption approach.

Restricting the file itself
This approach highly depends on the filesystem used to run the applications and the filesystem used
to store the application-data file (the one we want to restrict).
In windows, there is a command to manipulate with file access:
https://www.hexnode.com/mobile-device-management/help/script-to-change-file-permissions-on-windows-devices/
The user needs to be created beforehand.
In linux we can do that with chmod:
https://www.freecodecamp.org/news/linux-chmod-chown-change-file-permissions/
In docker:
https://stackoverflow.com/questions/26145351/why-doesnt-chown-work-in-dockerfile

Encrypting the contents
The advantage of this approach is that it is filesystem agnostic. The encryption and decryption can be done
directly in the application itself, when writing or reading from the file. We do not need username/password, but
a passphrase that serves the purpose of secret (or we can combine username+password into a passphrase). 
NodeJS has built-in library for this:
https://nodejs.org/docs/latest-v17.x/api/crypto.html

There are also some popular npm packages dealing with this topic:
https://www.npmjs.com/package/crypto-js
https://github.com/MauriceButler/cryptr

In both cases, I assume, that the passphrase/password would be stored as hashed/encrypted string in config file.

**Comment by DanaSunal** [comment]
Question: can a user create a file manually and only use putFilePath to let the application know, that this is the applicationData file? Should the user only use putFilePath (and the file will be created by the app?)

After discussion, encryption would be the way to go. We should be checking if we have permission to read/write the file, before attempting to do so.

**Comment by openBackhaul** [comment]
**Decision made during ImplementerCall at 14th of April 2023:**
Paths
- /core-model-1-4:control-construct/profile-collection/profile={uuid}/file-profile-1-0:file-profile-pac/file-profile-configuration/user-name:
- /core-model-1-4:control-construct/profile-collection/profile={uuid}/file-profile-1-0:file-profile-pac/file-profile-configuration/password:
cannot be supported with function as the operating systems do not support username/password protection of files.
The two paths just to be deleted from the ApplicationPattern OAS (further Spec files to be checked), until Operations team is addressing protection requirements.
