### ISSUE TITLE
Termination part in testsuite is always failing in all applications

### ISSUE THREAD

**Issue by DanaSunal** [openBackhaul/ApplicationPattern#695]
All requests in Termination part fail with test error, as dummyUri is not set. This is due to the previous request in PreTermination: _Clearing collection data_ : `pm.environment.clear();` 
The Termination requests all call for: `URI = pm.environment.get("dummyUri");`

I don't really see a purpose for the termination requests, why check ping.openbackhaul.com 4 times? Please either remove the requests or fix the Pre-request scripts.

This is for all applications.

**Comment by IswaryaaS** [comment]
Clearing has been pushed to PostTermination part
