### ISSUE TITLE
Add indexes for MATR & MWDI to ElasticSearch Index table

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/ApplicationPattern#698]
Indexes for ElasticSearch database in [index table](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/TestingApplications/Infrastructure/SdnLaboratory/FakeAddresses/IndexAliases.md) need to be added for MATR & MWDI

**Comment by openBackhaul** [comment]
Changed accordingly.
