### ISSUE TITLE
Update release-number of http-c to 2.0.1

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationPattern#713]
Current scenario:
In [load files](https://github.com/openBackhaul/ApplicationPattern/blob/develop/spec/ApplicationPattern%2Bconfig.json) of applications, the http-c/release-number(s) of client applications are 1.0.0. 

Problem statement:
Since, the services in v2.0.1 are not backward compatible with v1.0.0, while registering a v2.0.1 of an application, callbacks of /v1/bequeath-your-data-and-die gets failed during data transfer and subscription transfer phases. (because of difference in attribute names or presence of additional attributes). 

For example, 
- /v1/regard-application of EATL has different set of required attributes in v2.0.1 than in v1.0.0. While doing /v1/bequeath-your-data-and-die to v1.0.0, the /v1/regard-application from v1.0.0 towards v2.0.1 would fail which terminates the bequeathing process.
- This results in leaving behind v1.0.0 of EATL in RO for subscriptions like /v1/notify-approvals and also restricts it from getting deregistered (as /v1/deregister-application) would not be triggered. 
- This interrupts complete embedding of v2.0.1 and removing v1.0.0 (v2.0.1 cannot replace v1.0.0 for its functionality)

Proposal:
- Replace release-number of http-client instances of client applications to 2.0.1 from 1.0.0 in [spec/config.json](https://github.com/openBackhaul/ApplicationPattern/blob/develop/spec/ApplicationPattern%2Bconfig.json), [spec/services.yaml](https://github.com/openBackhaul/ApplicationPattern/blob/develop/spec/ApplicationPattern%2Bservices.yaml) file
- Replace uuid(s) pointing to version http-c/release-number of http-c, tcp-c and op-c instances from 1-0-0 to 2-0-1 in [spec/config.json](https://github.com/openBackhaul/ApplicationPattern/blob/develop/spec/ApplicationPattern%2Bconfig.json), [spec/services.yaml](https://github.com/openBackhaul/ApplicationPattern/blob/develop/spec/ApplicationPattern%2Bservices.yaml), [spec/forwardings.yaml](https://github.com/openBackhaul/ApplicationPattern/blob/develop/spec/ApplicationPattern%2Bforwardings.yaml)

Note: when 2.0.2 is released, the bequeathing process would be fine between 2.0.1 and 2.0.2 provided that services are backward compatible

**Comment by IswaryaaS** [comment]
Issues created in individual applications: 
https://github.com/openBackhaul/RegistryOffice/issues/423
https://github.com/openBackhaul/TypeApprovalRegister/issues/221
https://github.com/openBackhaul/ExecutionAndTraceLog/issues/254
https://github.com/openBackhaul/OamLog/issues/240
https://github.com/openBackhaul/AdministratorAdministration/issues/228
https://github.com/openBackhaul/ApplicationLayerTopology/issues/347
https://github.com/openBackhaul/OperationKeyManagement/issues/211

**Comment by openBackhaul** [comment]
**Result of discussion during the June 16, 2023 Implementation Call:**
The 2.0.1 specification does not take backward compatibility restrictions into account.
As a result, the bequeath-your-data-and-die process cannot run properly.
It has been decided to treat 2.0.1 like an initial release (1.0.0) and reinstall the platform from scratch (so update process).
Potential future 2.0.2 must respect backwards compatibility rules, and OldRelease must identify 2.0.1 as the ReleaseNumber in the ConfigFile.

**Comment by IswaryaaS** [comment]
@openBackhaul , Agreeing that the solution is applicable for individual applications. Hence closing the issue
