### ISSUE TITLE
Update the descriptions of property release-number from "update" to "find or update"

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationPattern#714]
Problem statement:
- In OAS, we have property release-number in services, which has descriptions like "update". 
- In very rare scenario, say if two instances of same application is available in config file and if an application is trying to  subscribe for a service, it updates the first occurring instance of the client application instead of updating the already existing instance that matches for application-name and release-number. 
- This result in two instances (duplicate entries) of same application-name/release-number combination. 

Detailed Example:

- Consider all applications already have http-c of AA v1.0.0. Now when AA v2.0.1 is trying to do /v1/register-application, after approval RO sends /v1/regard-application to other TAC applications. When an application like OamLog receives /v1/regard-application of AA v2.0.1, a new http-c shall be created. Now OL has two instances of AA (v1.0.0 and v2.0.1). 
- Later if OL is trying to do /v1/register-application, RO sends /v1/regard-application of OL to all TAC applications. When AA receives the request, as a callback, AA sends /v1/inquire-oam-request-approvals to OL. 
- As per specification(/v1/inquire-oam-request-approvals service has attributes oam-approval-application and oam-approval-application-release-number with descriptions like "find" for "oam-approval-application" and "update" for "oam-approval-application-release-number") , it would update the first instance of AA which is v1.0.0 of AA. 
- This would result in duplicity of AA in OL's config file. But it is expected to find v2.0.1 instance of AA and update that instance instead of updating v1.0.0

Proposal:
In order to avoid such cases, we can change the description of release-number property to "find or update" instead of "update" for following services.
- /v1/register-yourself
- /v1/embed-yourself
- /v1/redirect-service-request-information
- /v1/redirect-oam-request-information
- /v1/inquire-oam-request-approvals
- /v1/redirect-topology-change-information

Note: Based on decision made in this issue, issues shall be created in individual applications.

**Comment by IswaryaaS** [comment]
Similar issues in other applications:
 https://github.com/openBackhaul/RegistryOffice/issues/424
https://github.com/openBackhaul/TypeApprovalRegister/issues/222

**Comment by openBackhaul** [comment]
**Decision made during Implementation Call on June 16, 2023:**
_/v1/inquire-oam-request-approvals:_
It has to be attempted to find the ReleaseNumber first before potentially updating it.
Line 1755 ("update [/core-model-1-4:control-construct/logical-termination-point=*-1-0-0-http-c-aa-2-0-1-000/layer-protocol=0/http-client-interface-1-0:http-client-interface-pac/http-client-interface-configuration/release-number]'") has to be changed from "update ..." to "find or update ...".

Same for _/v1/register-yourself_, _/v1/embed-yourself_, _/v1/redirect-service-request-information_, _/v1/redirect-oam-request-information_ and _/v1/redirect-topology-change-information_.

**Comment by IswaryaaS** [comment]
_/v1/update-client_ also seems to have same kind of problem.. it is updating instance of current-application-name and current-release-number even if we have future-application-name and future-release-number
