### ISSUE TITLE
response-code is set as INTERNAL_SERVER_ERROR in catch block for all services

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationPattern#723]
In Controller/[filename].js , there is a catch block that catches if there is any exception thrown in any internal flow of the services. 
In all services, the catch block is commonly made the response-code as "INTERNAL_SERVER_ERROR" which would give 500 response code irrespective of the error. The error may be because of wrong input or something not supported or internal-server-error. 

})
      .catch(async function (responseBody) {
        responseBodyToDocument = responseBody;
        **responseCode = responseCodeEnum.code.INTERNAL_SERVER_ERROR;**
        let responseHeader = await restResponseHeader.createResponseHeader(xCorrelator, startTime, req.url);
        restResponseBuilder.buildResponse(res, responseCode, responseBody, responseHeader);
      });

Observed scenario:
POST inquireApplicationTypeApprovals with request body as EATL : actual error response : _The approval-application ExecutionAndTraceLog was not found._
Hope the response code should be 400 (as it is error from user side ) also i believe it should have error message as mentioned above. 

proposal:
We need to analyze possible response codes for all services (both in AP and in all individual applications) and update the response block for error condition. 

Note: after decision made, we can create issues in individual applications

**Comment by IswaryaaS** [comment]
Similar issues:
https://github.com/openBackhaul/RegistryOffice/issues/422
https://github.com/openBackhaul/TypeApprovalRegister/issues/220
https://github.com/openBackhaul/ExecutionAndTraceLog/issues/253
https://github.com/openBackhaul/OamLog/issues/239
https://github.com/openBackhaul/AdministratorAdministration/issues/227
https://github.com/openBackhaul/ApplicationLayerTopology/issues/346
https://github.com/openBackhaul/OperationKeyManagement/issues/210

**Comment by DanaSunal** [comment]
I've pushed a solution. The usage is of the custom Exception is prototyped in RegistryOffice. Any comments are welcome.

**Comment by PrathibaJee** [comment]
Many thanks for the solution.
We have changes in ApplicationPattern and Individualapplications.
In ApplicationPattern  , the parent HttpException shall be extended for future exceptions aswell. 
And the exported BadRequestHttpException shall be utilized to identify the thrown exception(from the RO PR).
We shall publish this change in ApplicationPattern in alpha.13. 

Kindly please create issues in individual applications as well.
After incorporating alpha.13 in individual application, we shall merge the changes made in individual application.(we shall make a note of this in the issues created in the individual applications)

**Comment by MartinSunal** [comment]
please, consider using existing lib with http errors https://www.npmjs.com/package/http-errors

**Comment by PrathibaJee** [comment]
Thanks for the feedback Martin. 
If we opt to use this npm package https://www.npmjs.com/package/http-errors , then we may not require the file included in [server/applicationPattern/applicationPattern/rest/server/HttpException.js](https://github.com/openBackhaul/ApplicationPattern/pull/730/files#diff-b31de8c33c433018d1b405914d4e5a4626a83ac471b6bd78d08111fb58b0e81a) as a part of this PR.
@DanaSunal , if you too have the same view , could you please remove the httpException file and also the change the prototype included in the RO. Thanks.
