### ISSUE TITLE
While regarding an application check needs to be included that application instance doesn't belong to NewRelease and OldRelease

### ISSUE THREAD

**Issue by vanithavalluripalli9** [openBackhaul/ApplicationPattern#736]
**Problem Description :** 

**Scenario#1:  Different releases of same application .**

When a new release of existing application is registered , it will update the http-c , tcp-c of Old Release in config file of New Release with the preceding application information provided in request body.

Once the application is approved and receives “embed-yourself” , a callback will be triggered to the old application’s “/v1/bequeath-your-data-and-die” .

When /v1/bequeath-your-data-and-die is executed, as part of callback PromptForBequeathingDataCausesTransferOfListOfApplications it will transfer the client applications from old Release to New Release by executing regard-application in New Release  . 

As part of execution of regard-application , it will find whether applications exists or not , if it exists it will update the instance with current details . 

During this process, if we are trying to regard preceding application client instance , it will find oldRelease client as preceding application instance instead of correct instance and it will update the  details which is not expected.

**Scenario#2:  Same Release of application but deployed in different address and port.**

When a same release but deployed in different address and port of existing application is registered , it will update the http-c , tcp-c of old Release in config file of New application with the preceding application information provided in request body.

Once the application is approved and receives “embed-yourself” , a callback will be triggered to the old application’s “/v1/bequeath-your-data-and-die” .

When /v1/bequeath-your-data-and-die is executed,it will update the NewRelease http-c,tcp-c with the new application details.
After, as part of callback PromptForBequeathingDataCausesTransferOfListOfApplications it will transfer the client applications from old  application to new application by executing regard-application in new application.

As part of execution of regard-application , it will find whether applications exists or not , if it exists it will update the instance with current details . 

During this process, if we are trying to regard same application client instance , it will find NewRelease client as same application instance instead of correct instance and it will update the  details which is not expected.

**Solution :** 

While regarding the application we should find  all the client application instances of application name , release number and get the application instance that doesn't belong to Old Release and New Release

> Priority:High
> AffectedFlow:Software Upgrade/RO:bequeath-your-data-and-die;

**Comment by PrathibaJee** [comment]
Issue needs to be created in individual applications of TAC except TAR.

**Comment by IswaryaaS** [comment]
Actual problem occurring : https://github.com/openBackhaul/AdministratorAdministration/issues/220

**Comment by PrathibaJee** [comment]
Based on the decision in https://github.com/openBackhaul/ExecutionAndTraceLog/issues/259 , this issue shall be fixed.

**Comment by IswaryaaS** [comment]
Related OAS issue : https://github.com/openBackhaul/ApplicationPattern/issues/758
