### ISSUE TITLE
Clarification required for detailed-logging-is-on feature

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationPattern#74]
We have the configurable attribute detailed-logging-is-on in the Application Pattern, which could be configured with either true or false values. This configuration restricts the number of attributes in the request-body of /v1/record-service-request that is being sent to the ExecutionAndTraceLog .

if detailed-logging-is-on = true, then the following attributes are sent in the request-body (which includes *required* attributes and other attributes)
        - x-correlator
        - trace-indicator
        - user
        - originator
        - application-name
        - application-release-number
        - operation-name
        - response-code
        - timestamp
        - stringified-body
        - stringified-response
 
If detailed-logging-is-on = false, then the following attributes are sent in the request-body (which includes only *required* attributes)
        - x-correlator
        - trace-indicator
        - user
        - originator
        - application-name
        - application-release-number
        - operation-name
        - response-code

If the above understanding is correct, can we update the description for /v1/redirect-service-request-information :: callbacks :: ServiceRequestCausesLoggingRequest :: requestBody to depict the different scenarios, since it is generalised. Kindly let us know your views.

**Comment by openBackhaul** [comment]
**Proposed solution:**
Descriptions of the three attributes  
- timestamp (line 1108),
- stringified-body (line 1111) and 
- stringified-response (line 1114)  

to be complemented with the statement ... '; only to be provided, if [/core-model-1-4:control-construct/logical-termination-point=*-0-0-1-op-c-0040/layer-protocol=0/operation-client-interface-1-0:operation-client-interface-pac/operation-client-interface-configuration/detailed-logging-is-on] == true.'

**Comment by openBackhaul** [comment]
@IswaryaaS: Sorry, couldn't understand your latest feedback. It looks like there should be different descriptions depending on the value of a variable during run time?!

**Comment by IswaryaaS** [comment]
The update proposed by @openBackhaul in [Clarify effect of detailed-logging-is-on](https://github.com/openBackhaul/ApplicationPattern/commit/bed2ece88f82a54ea85a20bb1328462a7929935d) now clearly depicts the restrictions for the logging data of service requests based on detailed-logging-is-on configuration.
