### ISSUE TITLE
updateClient :: release-number of future-release not updated as expected

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationPattern#741]
While doing update-client, it is expected that , if the future-application-name and future-release-number combination is not available in config file, and current-application-name and current-release-number combo is available in config file, the http-client of current-application-name and current-release-number combo is expected to be updated to future-application-name and future-release-number. 

But this scenario is not successful. 

Note: this scenario would be evident after solving https://github.com/openBackhaul/ApplicationPattern/issues/737#issuecomment-1600418082

**Comment by vanithavalluripalli9** [comment]
Fixed as part of https://github.com/openBackhaul/ApplicationPattern/pull/746
