### ISSUE TITLE
PromptingNewReleaseForUpdatingServerCausesRequestForBroadcastingInfoAboutBackwardCompatibleUpdateOfOperation triggers with incorrect attrbiute-name

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationPattern#745]
PromptingNewReleaseForUpdatingServerCausesRequestForBroadcastingInfoAboutBackwardCompatibleUpdateOfOperation is a callback of /v1/bequeath-your-data-and-die. This is expected to be triggered when receiving /v1/update-client of same application.

While triggering the request /v1/relay-operation-update to RO, responds with 400 error because of incorrect attribute name "release-number" . It has been implemented as "application-release-number"

**Comment by vanithavalluripalli9** [comment]
This is fixed as part of pull request  https://github.com/openBackhaul/ApplicationPattern/pull/746
