### ISSUE TITLE
Request to restrict OldRelease and NewRelease instances while fetching for http-c of application

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationPattern#758]
Problem Description :

When a new release of existing application is entering into the architecture, it will update the http-c , tcp-c of Old Release in config file with the preceding application information provided in request body of /v1/register-yourself.

Once the application is approved and receives “embed-yourself” , a callback will be triggered to the old application’s “/v1/bequeath-your-data-and-die” .

When /v1/bequeath-your-data-and-die is executed, as part of callback PromptForBequeathingDataCausesRequestForBroadcastingInfoAboutServerReplacement , the new application also shall receive /v1/update-client from RO. 

As part of execution of /v1/update-client , it will find whether applications exists or not , if it exists it will update the instance with given details .
- During this stage, the request-body will contain current-application-name and current-release-number attributes as same as OldRelease of this application. Because of this,  it is considering OldRelease client instance instead of correct instance.  
- Thus, operation-clients gets transferred from OldRelease instance to http-c instance with future-application-name and future-release-number combination. 

Proposal :

In OAS , for services like /v1/update-client, /v1/update-operation-client can we add description for application-name and release-number attributes like
`" **update shall be made considering http-c instances excluding OldRelease and NewRelease http-c instances** " . `

Note : In implementation, the OldRelease and NewRelease instances shall be considered from forwarding-constructs like PromptForEmbeddingCausesRequestForBequeathingData and PromptForBequeathingDataCausesTransferOfListOfApplications respectively. (The forwardings would vary based on application)

**Comment by openBackhaul** [comment]
**Change to be made at the OAS:**
In _ /v1/update-client_ and _/v1/update-operation-client_ the description has to be changed towards _"update shall be made excluding OldRelease and NewRelease http-c instances"_ at _application-name_ and _release-number_ attributes .

**Comment by IswaryaaS** [comment]
Apart from /v1/update-client and /v1/update-operation-client services, this change would also be required for _/v1/redirect-service-request-information, /v1/redirect-oam-request-information, /v1/inquire-oam-request-approvals and /v1/redirect-topology-change-information_

**Comment by openBackhaul** [comment]
@IswaryaaS please double check and comment:
.  
.  
_/v1/update-client_ and _/v1/update-operation-client_ are searching through all LTPs
```
find [/core-model-1-4:control-construct/logical-termination-point=*-1-0-0-http-c-*/layer-....
```
(regard ...=*-1-0-0-http-c-\* ...)  
and it makes sense to exclude OldRelease and NewRelease from this search
```
find, but not at OldRelease or NewRelease, [/core-model-1-4:control-construct/logical-termination-point=*-1-0-0-http-c-*/layer-....
```
.  
.  
_/v1/redirect-service-request-information_, _/v1/redirect-oam-request-information_, _/v1/inquire-oam-request-approvals_ and _/v1/redirect-topology-change-information_ are addressing concrete LTPs, a.g. 
```
find [/core-model-1-4:control-construct/logical-termination-point=*-1-0-0-http-c-eatl-2-0-1-000
```
(regard ...=*-1-0-0-http-c-eatl-2-0-1-000 ...)  
and it does not seem to make sense to exclude OldRelease and NewRelease from this "search", right?

**Comment by IswaryaaS** [comment]
Hi @openBackhaul , You are right. 

**_But,_** since we follow the practice of not hardcoding the uuid into the code, we use the attributes "application-name and release-number" for selecting the expected instance. In few cases, when OldRelease or NewRelease instances are updated with real-time values, this clash happens. 

For example, 

![image](https://github.com/openBackhaul/ApplicationPattern/assets/88484011/7a0a9d8f-7fc0-4a1d-afbd-967e9068d408)

If we exclude OldRelease and NewRelease (which would be found through forwardings in implementation), we can eliminate this ambiguity.

Kindly let me know your views.

**Comment by openBackhaul** [comment]
Added change to _/v1/redirect-service-request-information_, _/v1/redirect-oam-request-information_, _/v1/inquire-oam-request-approvals_ and _/v1/redirect-topology-change-information_.
