### ISSUE TITLE
/v1/register-yourself service make OAM layer non accessible

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/ApplicationPattern#763]
After executing the service /v1/register-yourself for validating the Continuous Integration / Service Idempotent? , OAM layer is non accessible.

❏ ServiceLayer / BasicPart / /v1/register-yourself / Continuous Integration / Service Idempotent?
↳ reference /core-model-1-4:control-construct
  ┌
  │ '\n' +
  │   '-----  /v1/register-yourself integration -- is serv
  │ ice idempotent? -------------------------------'
  └
  **GET http://x.x.x.x:3000/core-model-1-4:control-construct [200 OK, 178.74kB, 32ms]**

↳ Expected  /v1/register-yourself - service idempotent? **with no attributes**
  POST http://x.x.x.x:3000/v1/register-yourself [204 No Content, 254B, 223ms]
  ✓  POST /v1/register-yourself responds 204

↳ Expected  /v1/register-yourself - service idempotent? **with required attributes**
  POST http://x.x.x.x:3000/v1/register-yourself [204 No Content, 290B, 229ms]
  ✓  POST /v1/register-yourself responds 204 with only required attributes

↳ Expected  /v1/register-yourself - service idempotent? **with optional attributes**
  POST http://x.x.x.x:3000/v1/register-yourself [204 No Content, 289B, 590ms]
  ✓  POST /v1/register-yourself responds 204 with only required attributes

❏ ServiceLayer / BasicPart / /v1/register-yourself / Continuous Integration / request header parameter completeness
↳ reference /core-model-1-4:control-construct
  ┌
  │ '\n' +
  │   '-----  /v1/register-yourself integration -- request
  │  headers parameters completeness ---------------------
  │ ----------'
  └
  **GET http://x.x.x.x:3000/core-model-1-4:control-construct [401 Unauthorized, 423B, 44ms]**

Next steps:
Need to ,
1. verify whether issue is reproducible in local dev environment?
2. figure out the Rootcause ( in which scenario if the /v1/register-yourself the problem is occurring?)
3. provide proposal to solve the problem

> Priority:High

**Comment by vanithavalluripalli9** [comment]
This issue is solved after fixing the issue https://github.com/openBackhaul/TypeApprovalRegister/issues/244
