### ISSUE TITLE
http errors from oas3-tools are not compliant with openAPI structure

### ISSUE THREAD

**Issue by MartinSunal** [openBackhaul/ApplicationPattern#767]
oas3-tools does auth and validation of requests. If auth fails or request is not valid then oas3-tools returns http error with appropriate status code and body in format which is different than we have defined in openAPI specs.

Example of responses:
status code: 401
body:
```json
{
  "message": "unauthorized",
  "errors": [
    {
      "path": "/v1/update-ltp",
      "message": "unauthorized"
    }
  ]
}
```

status code: 400
body:
```json
{
  "message": "request.body should have required property 'uuid'",
  "errors": [
    {
      "path": ".body.uuid",
      "message": "should have required property 'uuid'",
      "errorCode": "required.openapi.validation"
    }
  ]
}
```

However, openAPI contains schemas for all http errors (400+) with structure like:
```json
{
  "code": 0,
  "message": "string"
}
```

That means an API consumer would expect response body in format as is described in openAPI but it will be different in reality.

We should either modify oas3-tools or change openAPI specification for all apps.
 > Priority:Low;
> AffectedFlow:None;

**Comment by PrathibaJee** [comment]
Thanks for the details @MartinSunal .
In the schema defined of errorDescription ,
```
schemas:
    errorDescription:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
```
We dont have the property additionalProperties:false , this means that the additional attribute "errors" is fine.
However , the required property "code" is not provided in the response.
Even if we include it from the serverside code , in the catch block of express-openapi-validator\dist\middlewares\openapi.security.js  , the included property "code"  is not getting considered for the response.
 ```
catch (e) {
            const message = ((_f = e === null || e === void 0 ? void 0 : e.error) === null || _f === void 0 ? void 0 : _f.message) || 'unauthorized';
            const err = types_1.HttpError.create({
                status: e.status,
                path: path,
                message: message,
 });
```
So , to fix this in the server side , it should be a fix in the openbackhaul-oas3-tools npm package. I guess this will be a minor change. If the change is minimal , then , shall we update the openbackhaul-oas3-tools. Kindly please let me know your views. 
Or if this is a major change , we shall further discuss this with @ThorstenHeinze  and get his views aswell. Thanks.

**Comment by MartinSunal** [comment]
@PrathibaJee I will take a look at openbackhaul-oas3-tools if we can add `code` to every http error.
