### ISSUE TITLE
Testsuite adjustments

### ISSUE THREAD

**Issue by DanaSunal** [openBackhaul/ApplicationPattern#769]
**pretty much every 'Response body completeness ' needs to be checked against correct parameters (usually the release number or description is wrong)**

- [x] ServiceLayer / BasicPart / /v1/inform-about-release-history / Acceptance / Response body completeness 

Provides invariant release date '17.12.2022' for release-number = 2.0.1 | expected '17.12.2021' to equal '17.12.2022'
Provides invariant changes 'Update on ApplicationPattern 2.0.1.' for release-number = 2.0.1 | expected 'Initial version.' to equal 'Update on ApplicationPattern 2.0.1.'
Invariant release number '1.0.0' could be found | expected undefined not to be an undefined

- [x] ServiceLayer / BasicPart / /v1/inform-about-release-history-in-generic-representation / Acceptance / Response body completeness

Provides expected object in response-value-list with field-name = 1.0.0 | expected undefined not to be an undefined
field-name = 1.0.0 has invariant value from Load file 'Initial version.' | Cannot read properties of undefined (reading 'value')
field-name = 1.0.0is of invariant data-type from Load file string | Cannot read properties of undefined (reading 'datatype')
field-name = 2.0.1 has invariant value from Load file 'Update on ApplicationPattern 2.0.1.' | expected 'Initial version.' to equal 'Update on ApplicationPattern 2.0.1.'

- [x] ServiceLayer / BasicPart / /v1/list-ltps-and-fcs / Acceptance / Response body completeness
- [x] ServiceLayer / BasicPart / /v1/redirect-topology-change-information / Acceptance / Response body completeness
- [x] OamLayer / IndividualPart / core / core-model-1-4:control-construct / GET / Acceptance / Response body completeness

same as above, release-numbers checked against 1.0.0

**Comment by IswaryaaS** [comment]
Fixed in individual applications. Hence closing the issue.
