### ISSUE TITLE
Merge develop branch to main branch and create tag v2.0.1_impl, v2.0.1_test

### ISSUE THREAD

**Issue by sunil-kumar-meena** [openBackhaul/ApplicationPattern#777]
Merging develop to main branch

- [ ] Create pull request to merge develop branch to main branch
- [ ] Create a tag v2.0.1_impl with the following details of the open issues in the version 2.
- [ ] Create a tag v2.0.1_test for publishing the testsuites for version 2.

## Implementation of ApplicationPattern v2.0.1
This release contains,

-  

## Open Issues
**Report timestamp : 
Total run Duration : 
Average response time : 
Total assertions : 
Total failures :
Total skipped test :** 

## Consistent Issues :
| Issue Number | assertions failures | 
| ------- | --------- | 
|  [[Issue_number]] | [[assertions_failures]]  | 

## Inconsistent Issues :
| Issue Number | assertions failures | 
| ------- | --------- | 
|  [[Issue_number]] | [[assertions_failures]]  |

**Comment by PrathibaJee** [comment]
Closing the issue as the v2.0.1_impl and v2.0.1_test tags are published.
