### ISSUE TITLE
/v1/update-client shall not update future-release-number and other attributes if the combination of application-name and release-number is not present in config-file

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationPattern#790]
/v1/update-client shall update the http-c or tcp-c only if one of the combination of {current-application-name and current-release-number} or  {future-application-name and future-release-number} are present. This update shall be made based on description in OAS. 

Problem:
In server, even if only future-application-name is present in config file with a different release-number, the attributes are getting updated even for release-number. Since, {future-application-name and future-release-number} is not present, this shall not be done. 

This behavior shall be restricted. 

> Priority:High;
> AffectedFlow:None;

**Comment by vanithavalluripalli9** [comment]
This is issue is closed with changes in PR https://github.com/openBackhaul/ApplicationPattern/pull/845
