### ISSUE TITLE
/v1/redirect-topology-change-information should not conatin release -list in the ResponseBody 

### ISSUE THREAD

**Issue by ManasaBM1** [openBackhaul/ApplicationPattern#803]
**Issue Description** : /v1/redirect-topology-change-information should not have release -list in the ResponseBody Since it is not mentioned in the Required Properties .

Response-Body :
```
 "release-list": [
        {
          "local-id": "0",
          "release-number": "1.0.0",
          "release-date": "17.12.2021",
          "changes": "Initial version."
        },
        {
          "local-id": "1",
          "release-number": "2.0.1",
          "release-date": "17.12.2022",
          "changes": "Update on ApplicationPattern 2.0.1."

        }
      ]

```

>> priority :low

**Comment by IswaryaaS** [comment]
Other than specified attributes, all shall be removed
![image](https://github.com/openBackhaul/ApplicationPattern/assets/88484011/c8cc7c48-4e2d-49e5-bb3d-53353418767e)
