### ISSUE TITLE
/v1/delete-ltp-and-dependents triggering for each ltp instance

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationPattern#812]
As per expectation, /v1/delete-ltp-and-dependents shall be sent for one ltp instance and all the dependents shall be deleted in ALT. 

But in applications, /v1/delete-ltp-and-dependents is being sent for all ltps being deleted. This needs to be resolved. 

Also, we could see 500 response code for few /v1/delete-ltp-and-dependents. 

>Priority:Medium;
>AffectedFlow:SDeregistration of application /ALT:/delete-ltp-and-dependents;

**Comment by IswaryaaS** [comment]
example: see EATL report :: SERVICELAYER / INDIVIDUALPART / /V1/DISREGARD-APPLICATION / ACCEPTANCE / DELETE LTP AND DEPENDENTS NOTIFIED? / CLIENT DELETE :: Expected ExecutionAndTraceLog/v1/list-records-of-flow

**Comment by DanaSunal** [comment]
I stumbled upon this issue by accident and it actually resolves  openBackhaul/ApplicationLayerTopology#409 . Also I already did a prototype for RO (as I needed to see if it resolves the 409 issue) and no change was required in RO itself. It also resolves (or I couldn't simulate any) the occasional 500 for delete-ltp.
