### ISSUE TITLE
OAS : detailed-logging-is-on attribute is missing under response : schema of /core-model-1-4:control-construct and /v1/list-ltps-and-fcs

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationPattern#83]
While accessing services like /v1/list-ltps-and-fcs and /core-model-1-4:control-construct , these services responds data of list of operation-client(s) along with the actual data. Here, ***detailed-logging-is-on*** is an optional attribute which is present only in operation-client ltp instance of **/v1/record-service-request of ExecutionAndTraceLog** (*-0-0-1-op-c-0040). 

In OAS, under schema specifications of /v1/list-ltps-and-fcs and /core-model-1-4:control-construct, under the path *logical-termination-point --> layer-protocol --> operation-client ltp --> operation-client-interface-configuration* specification , since the attribute "detailed-logging-is-on" is present only in one-instance among the operation-clients (an optional attribute), can we add it only under properties section(not in required section). 

![image](https://user-images.githubusercontent.com/88484011/159241846-59eb4d92-ca94-404a-8d01-db6328307976.png)

**Comment by openBackhaul** [comment]
**Decision:**
- Martin will try to correct the Express framework's oas3/tools module, so it is properly executing the validation of the response, with in 5 working days max.
- Prathiba will change the ApplicationPattern's code in such a way that the /v1/list-ltps-and-fcs service's response will not include the detailed-logging-is-on attribute.
- Thorsten will change the TAC applications' specifications and the applicationPattern in such a way that the detailed-logging-is-on attribute will be part of the properties section (but not the required section!) of the /core-model-1-4:control-construct path.

**Comment by openBackhaul** [comment]
**Update on 13th or May:**
In regard to the Specification aspects, this issue has been detailed and will be tracked in the following issues in future:
- #103 
- https://github.com/openBackhaul/RegistryOffice/issues/81
- https://github.com/openBackhaul/TypeApprovalRegister/issues/33
- https://github.com/openBackhaul/ExecutionAndTraceLog/issues/32
- https://github.com/openBackhaul/OamLog/issues/33
- https://github.com/openBackhaul/AdministratorAdministration/issues/27
- https://github.com/openBackhaul/ApplicationLayerTopology/issues/50
- https://github.com/openBackhaul/OperationKeyManagement/issues/14

**Comment by MartinSunal** [comment]
Validation is working as described here:
https://github.com/bug-hunters/oas3-tools/issues/43#issuecomment-1138295528

That means we need to change `res.end()` to be `res.json()` or `res.send()` in all application controllers.
