### ISSUE TITLE
update-ltp callback is returning response code as 500 instead of 404 if the the ALT application is not reachable.

### ISSUE THREAD

**Issue by ManasaBM1** [openBackhaul/ApplicationPattern#833]
**Problem description :**

When we execute /v1/regard-application with the below mentioned request body where address of ALT is being updated with dummy address :

**request-body :**

```
{
  "application-name": "ApplicationLayerTopology",
  "release-number": "2.0.1",
  "protocol": "HTTP",
  "address": {
    "domain-name": "ymdhg.j-ir.mdpvb-mr.burx"
  },
  "port": 3005
}
```

As there is change in the address, tcp-c LTP of ALT will be updated . As a consequence , update-ltp callback will be sent to ALT .

As the dummy address of ALT is not reachable it is expected that update-ltp callback will return 404 response code . But , response-code is being return as 500 instead of 400.

**Note** : The issue is being observed for protocol attribute as well.

**Comment by DanaSunal** [comment]
Fixed by : https://github.com/openBackhaul/ApplicationPattern/pull/802

```
recordServiceRequestFromClient - record service request from client with body {"x-correlator":"550e8400-e29b-11d4-a716-446655440000","trace-indicator":"1.3.1.1","user":"User Name","originator":"ApplicationLayerTopology","application-name":"ApplicationLayerTopology","release-number":"2.0.1","operation-name":"/v1/update-ltp","response-code":408} failed with response status: 408
```

**Comment by ManasaBM1** [comment]
Thank you .
