### ISSUE TITLE
Update AuthorizingService to consider RequestTimeOut as unavailability of the server

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/ApplicationPattern#844]
In the applicationPattern\services\AuthorizingService.js , we have the following logics to validate the authentication.
1. If the client connects to the AdministratorAdministration application , and receives a response code 200 with response body responseBody["oam-request-is-approved"]=true , then the authentication is valid
2. If the client connects to the AdministratorAdministration application , and receives a response code 200 with response body responseBody["oam-request-is-approved"]=false , then the authentication is not valid 
3. But if the client is not able to connect to the AdministratorAdministration application , previously , the REST client will consider this as 404 response code , and so , the applicationPattern\services\AuthorizingService.js consider this 404 as the server unavailability.
**Change Request :** 
In the recent PR  https://github.com/openBackhaul/ApplicationPattern/pull/802, this was changed. So , the consuming logic in applicationPattern\services\AuthorizingService.js also should be updated as per this change.

**Comment by IswaryaaS** [comment]
@ManasaBM1 , please check if this issue is resolved as per https://github.com/openBackhaul/ApplicationPattern/issues/844#issuecomment-1671315190. If so, kindly close the issue. 
Many thanks in advance.

**Comment by PrathibaJee** [comment]
Requested changes are already delivered as a part of https://github.com/openBackhaul/ApplicationPattern/pull/840. Hence closing this issue.
