### ISSUE TITLE
Update fake ip address table with updated Controller entries

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/ApplicationPattern#849]
current content:
![image](https://github.com/openBackhaul/ApplicationPattern/assets/57349523/76477ca4-8f61-45a3-9bac-56136f96110e)

While creating the MWDI v1.0.0 spec other values have been used, so the following entries need to be changed:
- Component = OpenDay**L**ight   (upper case L)
- new abbreviation: ODL

**Comment by openBackhaul** [comment]
Done.
