### ISSUE TITLE
Request to make attributes old-release-address , old-release-protocol, old-release-port optional for service /v1/embed-yourself.

### ISSUE THREAD

**Issue by vanithavalluripalli9** [openBackhaul/ApplicationPattern#871]
**Problem Description:** 

To test the software upgrade test suite , OldRelease,NewRelease tcp-c details are set through fake ip script before start of the application.

After that when the application is started it will trigger automatic register-yourself with no request body in application  . This is will trigger callback register-application to RO as mentioned below : 

-> **register-application to RO** with **request body** 
`{"application-name":"AdministratorAdministration","release-number":"2.0.1","embedding-operation":"/v1/embed-yourself","client-update-operation":"/v1/update-client","operation-client-update-operation":"/v1/update-operation-client","tcp-server-list":[{"protocol":"HTTP","port":3004,"address":{"ip-address":{"ipv-4-address":"127.0.0.1"}}}
`

As application is already approved , 
-> **embed-yourself is sent by RO to application with request body** 
`{"registry-office-application":"RegistryOffice","registry-office-application-release-number":"2.0.1","relay-server-replacement-operation":"/v1/relay-server-replacement","relay-operation-update-operation":"/v1/relay-operation-update","deregistration-operation":"/v1/deregister-application","registry-office-address":{"ip-address":{"ipv-4-address":"1.1.3.8"}},"registry-office-port":3008,"registry-office-protocol":"HTTP","old-release-protocol":"HTTP","old-release-address":{"ip-address":{"ipv-4-address":"127.0.0.1","old-release-port":3004}`

**Note : For above examples the example application taken is AA running in port 3004 .**

Once the embed-yourself is executed in the application OldRelease port that is set by fake ip script is replaced with the old-release-port that is sent in the request body of embed yourself which is current server details as preceeding application details are not provided.

**Proposal :** 

Currently . as per OAS the below mentioned properties are required request body properties for service /v1/embed-yourself.
```
  required:
      - registry-office-application
      - registry-office-application-release-number
      - relay-server-replacement-operation
      - relay-operation-update-operation
      - deregistration-operation
      - registry-office-protocol
      - registry-office-address
      - registry-office-port
      - old-release-protocol
      - old-release-address
      - old-release-port

```
As , callback bequeath-your-data-and-die for embed-yourself service is only trrigered when oldRelease 
**application-name != "OldRelease"** . Can we make below mentioned properties as optional properties of request body for the service /v1/embed-yourself.

```
- old-release-protocol
- old-release-address
- old-release-port
```

**Comment by openBackhaul** [comment]
I understood that
- the new applications gets instantiated with proper info about the OldRelease.
- as new application -> RO://v1/register-application does not contain info about the OldRelease,
consequent RO -> new application://v1/embed-yourself does definitively not contain useful info.

Further on, I assume that the info about the OldRelease shall remain in /v1/embed-yourself for being able to trigger the embedding either manually or with tools different from RO.

**Comment by vanithavalluripalli9** [comment]
Hi Thorsten , I would like to apologize that we couldn't discuss the issue . We had a plan to discuss this in the upcoming call .

Thank you for accepting the proposal.
