### ISSUE TITLE
In implementation of the service /v1/embed-yourself , old release details needs to be updated only if preceeding application details are provided.

### ISSUE THREAD

**Issue by vanithavalluripalli9** [openBackhaul/ApplicationPattern#905]
As per the issue https://github.com/openBackhaul/ApplicationPattern/issues/871,  the old release details are made optional for the service /v1/embed-yourself .

In implementation of the service /v1/embed-yourself , old release details needs to be updated only if preceeding application details are provided in request body.

**Comment by PrathibaJee** [comment]
Solution for this problem is same as the one for the issue https://github.com/openBackhaul/ApplicationPattern/issues/950. Hence closing this issue.
