### ISSUE TITLE
Understanding description of application-name property in services of Application Pattern

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationPattern#91]
Few basic services have application-name and release-number in their request-body which after received by a server involves in creating or updating the logical-termination-point. From the descriptions provided on Application Pattern specification, we could find differences on the restrictions to be made on creating the logical-termination-point.
For example,
 -  /v1/register-yourself, /v1/embed-yourself - registry-office-application - "**find or create**" under uuid *-0-0-1-http-c-0020
 - /v1/redirect-service-request information - service-log-application - "**find**" under uuid "*-0-0-1-http-c-0040"
 - /v1/redirect-oam-request-information - oam-log-application - "**find**" under uuid  "*-0-0-1-http-c-0050"
 
In the above cases, we can find two scenarios "find or create" and simply "find" which leads to following understandings:

**case 1**: "find or create"  /v1/register-yourself and /v1/embed-yourself
   In this case, we are searching for the received registry-office-application-name in uuid *-0-0-1-http-c-0020,
  -  if the application-name could not be found in the given uuid or if the given uuid itself is not present in the ltp list, then a new instance (a set of http-c, tcp-c and op-c) needs to be created, then further fc update happens accordingly. This new application will be considered for further forwarding in registration process.
  - This leads to an understanding that It is acceptable that even if the request is carrying any other application-name (other than Registry Office), that application will be configured for further registration process. This makes us understand that there is no restrictions that in future, Registry Office application-name can be renamed
  
**case 2**: only "find" in /v1/redirect-service-request information or /v1/redirect-oam-request information
  In this case, we are searching for received subscriber-application-name (ExecutionAndTraceLog or OAM log) in the given uuid,
 - if the application-name is not present in the given uuid, no further action is taken (no ltp creation or update happens). 
 - This makes us understand that Only ExecutionAndTraceLog / OamLog application-name is allowed for subscription and no other application-name is allowed.

Possible options:
- If case 1 is correct (applications have no restrictions to name change in future), then descriptions for subscriber-application under /v1/redirect-service-request information and /v1/redirect-oam-request information could also be updated as "find or create"
- If case 2 is correct (only currently used names will be followed in future) , then all the similar descriptions could be changed.
- or please clarify whether the application-name will not be updated only for ExecutionAndTraceLog and OAMLog applications and for other applications there is a possibility of application-name update.

**Comment by openBackhaul** [comment]
Case 2 shall support assuring that logging data will not be redirected to destructive targets.

**Comment by openBackhaul** [comment]
**Intermediate status of discussion on 13.05.:**
Either /core-model-1-4:control-construct/logical-termination-point={uuid}/layer-protocol=0/http-client-interface-1-0:http-client-interface-pac/http-client-interface-capability/application-name to be completed by a PUT operation to facilitate changing the application name or the formed decision to be inverted an a "or create" to be kept.

**Comment by openBackhaul** [comment]
In the [description of this issue](https://github.com/openBackhaul/ApplicationPattern/issues/91#issue-1218600854), case 1 and case 2 are describing the expected behavior.  
Possible option 3 is correct, it shall not be possible to re-direct logging information to other applications.  

As already [commented on 29th of April](https://github.com/openBackhaul/ApplicationPattern/issues/91#issuecomment-1113005945), /v1/inquire-oam-request-approvals :: oam-approval-application shall be corrected to "find" ("or create" shall be deleted).

To facilitate changing application names during runtime, /core-model-1-4:control-construct/logical-termination-point={uuid}/layer-protocol=0/http-client-interface-1-0:http-client-interface-pac/http-client-interface-capability/application-name to be completed by a PUT operation.
