### ISSUE TITLE
Clarification regarding the response of the API /v1/inform-about-preceding-release

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/ApplicationPattern#933]
This API **“/v1/inform-about-preceding-release”**  is to get the **application-name and release-number** of the **old release** of an application.
We know that , in the initial configuration file of all the application , **the application-name of the oldRelease is “OldRelease”**.

If the **registered application** is the very first version and **don’t have a previous version** , 
then,
the application-name of the old-release is OldRelease. 

So, the response of the /v1/inform-about-preceding-release will be something like this , 
```
{
  "application-name": "OldRelease",
  "release-number": "1.0.1"
}
```

Kindly please let us know shall we produce a result like this ? 
(or) 
we shall not send a response code!=200 meaning that there is no previous version of this application is available.

Also we shall look into a related issue in RegistryOffice  https://github.com/openBackhaul/RegistryOffice/issues/527

**Comment by openBackhaul** [comment]
Yes, please produce a result like this:
```
{
  "application-name": "OldRelease",
  "release-number": "1.0.1"
}
```

The response code shall relate to the communication and not the content of the message.

**Comment by PrathibaJee** [comment]
Thank you for the clarification. Closing the issue.
