### ISSUE TITLE
To remove security from the API /v1/inform-about-preceding-release

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/ApplicationPattern#934]
Since the information provided in the response of the API /v1/inform-about-preceding-release is not that confidential , 
shall we not protect it with an operation-key. 
So , proposing to remove the security of this API.

If this proposal is accepted , then we shall also remove the ApprovingApplicationCausesPreparingTheEmbedding.CreateLinkToGetOldRelease forwarding from the RegistryOffice application.

**Comment by openBackhaul** [comment]
Changed as proposed.
