### ISSUE TITLE
To modify the request-body attribute future-port to port in the API /v1/update-client-of-subsequent-release

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/ApplicationPattern#935]
In the OAS , following are the attributes in the required section of the API /v1/update-client-of-subsequent-release , 
```
                - application-name
                - release-number
                - protocol
                - address
                - port
```

But , in the **property section , the attribute “port” is missing. Instead , we have an attribute future-port.**

**Proposal :**
The “future-port” in the property section shall be changed to “port”

**Comment by openBackhaul** [comment]
Changed as proposed.
