### ISSUE TITLE
To record the service request of the new APIs in the EATL application

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/ApplicationPattern#936]
The following API’s uuids are not included as an output fc-port of the forwarding ServiceRequestCausesLoggingRequest.

1. xx-1-0-0-op-s-bm-013	/v1/dispose-remainders-of-deregistered-application
2. xx-1-0-0-op-s-bm-014	/v1/inform-about-preceding-release
3. xx-1-0-0-op-s-bm-015	/v1/update-client-of-subsequent-release

**Proposal :**
The above mentioned uuids shall be included as an output fc-port of the forwarding ServiceRequestCausesLoggingRequest

**Comment by openBackhaul** [comment]
Had already been changed as proposed.
