### ISSUE TITLE
To include PromptForRegisteringCausesRegistrationRequest2 forwarding-construct in the CONFIG file

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/ApplicationPattern#939]
As per the OAS , /v1/register-yourself  has the following 2 callbacks, 
PromptForRegisteringCausesRegistrationRequest 
PromptForRegisteringCausesRegistrationRequest2

As per the description mention in the PromptForRegisteringCausesRegistrationRequest callback , both this callbacks needs to be executed.
```
Starting from RO v2.1.0, PromptForRegisteringCausesRegistrationRequest shall be executed first and 
PromptForRegisteringCausesRegistrationRequest2 second. Sequence shall be kept regardless of the respective HTTP response codes.'
```
But , in the config file , we dont have a forwarding-construct for the callback PromptForRegisteringCausesRegistrationRequest2.

**Proposal :**
A forwarding-construct for the PromptForRegisteringCausesRegistrationRequest2 similar to the PromptForRegisteringCausesRegistrationRequest callback needs to be included in the ,
- config.json
- ApplicationPattern+forwardings.yaml

**Comment by openBackhaul** [comment]
Added a seconding forwarding in both CONFIGfile and ForwardingList.
