### ISSUE TITLE
RequestHeader constructor to initialize trace-indicator as a string instead of integer

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationPattern#964]
In ApplicationPattern package, _onf-core-model-ap/applicationPattern/rest/client/RequestHeader_ , the class has a constructor that initializes a new trace-indicator if the incoming request does not have one. 
Currently, this is being initialized as a integer. 

Proposal:
The trace-indicator shall be initialized as string like below code snippet. 
```
this.traceIndicator = traceIndicator;
        if (traceIndicator == undefined || traceIndicator.length == 0) {
            this.traceIndicator = ‘1’;
        }. 
```

**Comment by PrathibaJee** [comment]
Issue merged to branch v2.1.1_impl as a part of the PR https://github.com/openBackhaul/ApplicationPattern/pull/967.
Hence closing this issue.
