### ISSUE TITLE
support to tcpList in LogicalTerminationPointConfiguration shall be made as TcpObject 

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationPattern#968]
Since from version 2.1.0, an application shall expect to have only one tcp-client instance. So, we could update the 
1. constructor in onf-core-model-ap/applicationPattern/onfModel/services/models/logicalTerminationPoint/ConfigurationInput
2. functions in and dependent and called upon onf-core-model-ap/applicationPattern/onfModel/services/LogicalTerminationPointServices 

to have attribute tcpObject instead of tcpList. 

Kindly let me know your views.

**Comment by PrathibaJee** [comment]
Included this change in the latest referred Pull request. Hence closing this issue.
