### ISSUE TITLE
Add : domain name in the TCP Server and client configuration

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/ApplicationPattern#97]
This proposal is to include the domain-name in the tcp-client and tcp-server logical-termination-point to enable seamless communication in a container orchestrator environment. (The proposal assumes that we proceed with Kubernetes(K8s))

Please find the attached document that consists of the details about this proposal.
[220505 Proposal to include service name in TCP Server and Client.docx](https://github.com/openBackhaul/ApplicationPattern/files/8630839/220505.Proposal.to.include.service.name.in.TCP.Server.and.Client.docx)

**Comment by openBackhaul** [comment]
At least the following documents have to be changed:
- LOADfile (CONFIGfile)
  - [ ] all TcpClients
  - [ ] all TcpServers
- OAS
  - [ ] Line 7 url statement to be change to application name
  - [ ] all service bodies containing *address and *port
  - [ ] all service body examples containing *address and *port
  - [ ] all service response bodies containing *address and *port
  - [ ] all service response body examples containing *address and *port
  - [ ] all callbacks bodies containing *address and *port
  - [ ] all callbacks body examples containing *address and *port
  - [ ] all callbacks response bodies containing *address and *port
  - [ ] all callbacks response body examples containing *address and *port
  - [ ] control-construct :: tcp-server
  - [ ] control-construct :: tcp-client
  - [ ] GET control-construct :: ... :: tcp-server-interface-pac :: ... :: ipv-4-address
  - [ ] PUT control-construct :: ... :: tcp-server-interface-pac :: ... :: ipv-4-address
  - [ ] GET control-construct :: ... :: tcp-client-interface-pac :: ... :: ipv-4-address
  - [ ] PUT control-construct :: ... :: tcp-client-interface-pac :: ... :: ipv-4-address
- [ ] ClassDiagram.pptx documentation

**Comment by openBackhaul** [comment]
Implementation aspects will also be tracked in one or several different issues (this one gets assigned back to me).
Since all specification related aspects have been completed, issue can be closed.
