### ISSUE TITLE
OAS schema : include pattern in description for operation-name attribute in request-body

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationPattern#98]
Few services in the OAS has attribute operation-name in the request-body.

As per understanding, the operation-name(s) in Application Pattern has the following pattern "**/version/actual operation-name**". Also, as the future updates in operation-servers will involve only updating the version number and the operation-name remaining the same, can we include specific pattern for each operation-name in the description.

For example,
In a basic service /v1/register-yourself, where the application-name=RegistryOffice, registration-operation=/v1/register-application, Here, could a pattern be defined for the attribute registration-operation

**Comment by openBackhaul** [comment]
Adding a pattern to the application-name attributes would allow responding with an explicit http response code in case of faulty input parameter values, but it would also strengthen coupling between the applications, which contributes the architecture to become more rigid. It would be preferred to continue without a pattern here.
