### ISSUE TITLE
Clarification required for operation-name attribute specification "minLength"

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationPattern#99]
In /v1/register-application, an Individual service of RegistryOffice application, the operations **embedding-operation** and **client-update-operation** has a restriction **minLength: 3** in OAS, which no other operations in ApplicationPattern are specified with. 
So, please clarify if this is applicable to other operations as well.

**Comment by openBackhaul** [comment]
**Decision:**
minLength stereotype at all application-name attributes at all applications shall be harmonized.
An issue with the following text shall be created in all TAC applications and the ApplicationPatter repositories: "minLength:6 shall be defined at all operation-name attributes."
