### ISSUE TITLE
To remove schema description for the request-header x-correlator and trace-indicator

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationPattern#990]
In OAS, we have descriptions for request-header parameters x-correlator and trace-indicator in the path "components :: parameters". 

![image](https://github.com/user-attachments/assets/8731a071-9402-4d73-9d43-fd75c1359dd1)

Problem:
- As per the description provided, Empty string accepted from external applications. which is contradicting with the required: true constraint provided.
- Also, this description explains that the incoming request can have x-correlator provided as an empty string. As per given pattern, which does not allow an empty string.

Proposal:
- We shall remove the schema description: 'Empty string accepted from external applications.'  from definition of both x-correlator and trace-indicator attributes.

**Comment by openBackhaul** [comment]
As proposed, both descriptions removed from the common components of the ApplicationPattern.
